/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountChargesRequest } from './accountChargesRequest';


export interface AccountRequest { 
    allowDividendCalculationForInactiveClients?: string;
    applicationDate?: string;
    approvedDate?: string;
    charges?: Array<AccountChargesRequest>;
    clientId?: number;
    currencyCode?: string;
    dateFormat?: string;
    digitsAfterDecimal?: number;
    externalId?: string;
    id?: number;
    inMultiplesOf?: string;
    locale?: string;
    lockinPeriodFrequency?: number;
    lockinPeriodFrequencyType?: string;
    minimumActivePeriod?: number;
    minimumActivePeriodFrequencyType?: string;
    numberOfShares?: number;
    productId?: number;
    purchasedDate?: string;
    requestedShares?: number;
    savingsAccountId?: number;
    submittedDate?: string;
    unitPrice?: number;
}

