/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeValueData } from './codeValueData';


export interface AddressData { 
    addressId?: number;
    addressLine1?: string;
    addressLine2?: string;
    addressLine3?: string;
    addressType?: string;
    addressTypeId?: number;
    addressTypeIdOptions?: Array<CodeValueData>;
    city?: string;
    clientID?: number;
    countryId?: number;
    countryIdOptions?: Array<CodeValueData>;
    countryName?: string;
    countyDistrict?: string;
    createdBy?: string;
    createdOn?: string;
    isActive?: boolean;
    latitude?: number;
    longitude?: number;
    postalCode?: string;
    stateName?: string;
    stateProvinceId?: number;
    stateProvinceIdOptions?: Array<CodeValueData>;
    street?: string;
    townVillage?: string;
    updatedBy?: string;
    updatedOn?: string;
}

