/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppUserData } from './appUserData';
import { ProcessingResultLookup } from './processingResultLookup';


export interface AuditSearchData { 
    actionNames?: Array<string>;
    appUsers?: Array<AppUserData>;
    entityNames?: Array<string>;
    statuses?: Array<ProcessingResultLookup>;
}

