/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MultiPart } from './multiPart';
import { ContentDisposition } from './contentDisposition';
import { MediaType } from './mediaType';
import { BodyPartParameterizedHeaders } from './bodyPartParameterizedHeaders';
import { BodyPartHeaders } from './bodyPartHeaders';


export interface BodyPart { 
    contentDisposition?: ContentDisposition;
    entity?: object;
    headers?: BodyPartHeaders;
    mediaType?: MediaType;
    messageBodyWorkers?: object;
    parameterizedHeaders?: BodyPartParameterizedHeaders;
    parent?: MultiPart;
    providers?: object;
}

