/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CalendarRequest { 
    dateFormat?: string;
    frequency?: string;
    interval?: string;
    locale?: string;
    repeating?: string;
    repeatsOnDay?: string;
    startDate?: string;
    title?: string;
    typeId?: string;
}

