/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageCashierTransactionData } from './pageCashierTransactionData';


export interface CashierTransactionsWithSummaryData { 
    cashierId?: number;
    cashierName?: string;
    cashierTransactions?: PageCashierTransactionData;
    netCash?: number;
    officeName?: string;
    sumCashAllocation?: number;
    sumCashSettlement?: number;
    sumInwardCash?: number;
    sumOutwardCash?: number;
    tellerId?: number;
    tellerName?: string;
}

