/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CashierData } from './cashierData';


export interface CashiersForTeller { 
    cashiers?: Array<CashierData>;
    officeId?: number;
    officeName?: string;
    tellerId?: number;
    tellerName?: string;
}

