/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChargeRequest { 
    active?: boolean;
    amount?: number;
    chargeAppliesTo?: number;
    chargeCalculationType?: number;
    chargePaymentMode?: number;
    chargeTimeType?: number;
    currencyCode?: string;
    enablePaymentType?: boolean;
    feeFrequency?: string;
    feeInterval?: string;
    feeOnMonthDay?: string;
    locale?: string;
    maxCap?: number;
    minCap?: number;
    monthDayFormat?: string;
    name?: string;
    paymentTypeId?: number;
    penalty?: boolean;
}

