/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxGroup } from './taxGroup';
import { GLAccount } from './gLAccount';
import { PaymentType } from './paymentType';
import { ChargeFeeOnMonthDay } from './chargeFeeOnMonthDay';


export interface Charge { 
    account?: GLAccount;
    active?: boolean;
    allowedClientChargeCalculationType?: boolean;
    allowedClientChargeTime?: boolean;
    allowedLoanChargeTime?: boolean;
    allowedSavingsChargeCalculationType?: boolean;
    allowedSavingsChargeTime?: boolean;
    amount?: number;
    annualFee?: boolean;
    chargeCalculation?: number;
    chargePaymentMode?: number;
    chargeTimeType?: number;
    clientCharge?: boolean;
    currencyCode?: string;
    deleted?: boolean;
    disbursementCharge?: boolean;
    enableFreeWithdrawal?: boolean;
    enablePaymentType?: boolean;
    feeInterval?: number;
    feeOnMonthDay?: ChargeFeeOnMonthDay;
    frequencyFreeWithdrawalCharge?: number;
    id?: number;
    incomeAccountId?: number;
    loanCharge?: boolean;
    maxCap?: number;
    minCap?: number;
    monthlyFee?: boolean;
    name?: string;
    'new'?: boolean;
    overdueInstallment?: boolean;
    paymentType?: PaymentType;
    penalty?: boolean;
    percentageOfApprovedAmount?: boolean;
    percentageOfDisbursementAmount?: boolean;
    restartFrequency?: number;
    restartFrequencyEnum?: number;
    savingsCharge?: boolean;
    taxGroup?: TaxGroup;
}

