/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeValueData } from './codeValueData';


export interface ClientFamilyMembersData { 
    age?: number;
    clientId?: number;
    dateOfBirth?: string;
    firstName?: string;
    gender?: string;
    genderId?: number;
    genderIdOptions?: Array<CodeValueData>;
    id?: number;
    isDependent?: boolean;
    lastName?: string;
    maritalStatus?: string;
    maritalStatusId?: number;
    maritalStatusIdOptions?: Array<CodeValueData>;
    middleName?: string;
    mobileNumber?: string;
    profession?: string;
    professionId?: number;
    professionIdOptions?: Array<CodeValueData>;
    qualification?: string;
    relationship?: string;
    relationshipId?: number;
    relationshipIdOptions?: Array<CodeValueData>;
}

