/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalId } from './externalId';
import { EnumOptionData } from './enumOptionData';


export interface ClientSearchData { 
    accountNumber?: string;
    activationDate?: string;
    createdDate?: string;
    displayName?: string;
    externalId?: ExternalId;
    id?: number;
    mobileNo?: string;
    officeId?: number;
    officeName?: string;
    status?: EnumOptionData;
}

