/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Code } from './code';


export interface CodeValue { 
    active?: boolean;
    code?: Code;
    description?: string;
    id?: number;
    label?: string;
    mandatory?: boolean;
    'new'?: boolean;
    position?: number;
}

