/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeValue } from './codeValue';


export interface Code { 
    id?: number;
    name?: string;
    'new'?: boolean;
    systemDefined?: boolean;
    values?: Set<CodeValue>;
}

