/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalId } from './externalId';


export interface CommandWrapper { 
    actionName?: string;
    cacheResource?: boolean;
    changePasswordOperation?: boolean;
    clientId?: number;
    commandId?: number;
    create?: boolean;
    createDatatable?: boolean;
    creditBureauId?: number;
    currencyResource?: boolean;
    datatableResource?: boolean;
    'delete'?: boolean;
    deleteDatatable?: boolean;
    deleteMultiple?: boolean;
    deleteOneToOne?: boolean;
    deleteOperation?: boolean;
    entityId?: number;
    entityName?: string;
    fullFilSurvey?: boolean;
    groupId?: number;
    href?: string;
    idempotencyKey?: string;
    interestPauseCreateResource?: boolean;
    interestPauseDeleteResource?: boolean;
    interestPauseResource?: boolean;
    interestPauseUpdateResource?: boolean;
    jobName?: string;
    json?: string;
    loanDisburseDetailResource?: boolean;
    loanExternalId?: ExternalId;
    loanId?: number;
    noteResource?: boolean;
    officeId?: number;
    organisationCreditBureauId?: number;
    passwordPreferencesResource?: boolean;
    permissionResource?: boolean;
    productId?: number;
    registerDatatable?: boolean;
    registerSurvey?: boolean;
    sanitizeJsonKeys?: Set<string>;
    savingsId?: number;
    subentityId?: number;
    surveyResource?: boolean;
    taskPermissionName?: string;
    templateId?: number;
    transactionId?: string;
    update?: boolean;
    updateDatatable?: boolean;
    updateDisbursementDate?: boolean;
    updateMultiple?: boolean;
    updateOneToOne?: boolean;
    updateOperation?: boolean;
    userResource?: boolean;
    workingDaysResource?: boolean;
}

