/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DelinquencyRangeData } from './delinquencyRangeData';


export interface DelinquencyBucketData { 
    id?: number;
    name?: string;
    ranges?: Array<DelinquencyRangeData>;
}

