/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface DepositAccountOnHoldTransactionData { 
    amount?: number;
    id?: number;
    loanAccountNo?: string;
    loanClientName?: string;
    loanId?: number;
    reversed?: boolean;
    savingsAccountNo?: string;
    savingsClientName?: string;
    savingsId?: number;
    transactionDate?: string;
    transactionType?: EnumOptionData;
}

