/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExternalTransferDataDetails { 
    detailsId?: number;
    totalFeeChargesOutstanding?: number;
    totalInterestOutstanding?: number;
    totalOutstanding?: number;
    totalOverpaid?: number;
    totalPenaltyChargesOutstanding?: number;
    totalPrincipalOutstanding?: number;
}

