/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilterData { 
    operator?: FilterData.OperatorEnum;
    values?: Array<string>;
}
export namespace FilterData {
    export const OperatorEnum = {
        Eq: 'EQ',
        Neq: 'NEQ',
        Gte: 'GTE',
        Lte: 'LTE',
        Gt: 'GT',
        Lt: 'LT',
        Like: 'LIKE',
        Nlike: 'NLIKE',
        Btw: 'BTW',
        Nbtw: 'NBTW',
        In: 'IN',
        Nin: 'NIN',
        Null: 'NULL',
        Nnull: 'NNULL'
    } as const;
    export type OperatorEnum = typeof OperatorEnum[keyof typeof OperatorEnum];
}


