/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FinancialActivityData { 
    id?: number;
    mappedGLAccountType?: FinancialActivityData.MappedGLAccountTypeEnum;
    name?: string;
}
export namespace FinancialActivityData {
    export const MappedGLAccountTypeEnum = {
        Asset: 'ASSET',
        Liability: 'LIABILITY',
        Equity: 'EQUITY',
        Income: 'INCOME',
        Expense: 'EXPENSE'
    } as const;
    export type MappedGLAccountTypeEnum = typeof MappedGLAccountTypeEnum[keyof typeof MappedGLAccountTypeEnum];
}


