/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GLAccountData } from './gLAccountData';
import { FinancialActivityData } from './financialActivityData';


export interface FinancialActivityAccountData { 
    financialActivityData?: FinancialActivityData;
    financialActivityOptions?: Array<FinancialActivityData>;
    glAccountData?: GLAccountData;
    glAccountOptions?: { [key: string]: Array<GLAccountData>; };
    id?: number;
}

