/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FloatingRatePeriodData } from './floatingRatePeriodData';
import { EnumOptionData } from './enumOptionData';


export interface FloatingRateData { 
    createdBy?: string;
    createdOn?: string;
    id?: number;
    interestRateFrequencyTypeOptions?: Array<EnumOptionData>;
    isActive?: boolean;
    isBaseLendingRate?: boolean;
    modifiedBy?: string;
    modifiedOn?: string;
    name?: string;
    ratePeriods?: Array<FloatingRatePeriodData>;
}

