/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FloatingRatePeriodData { 
    createdBy?: string;
    createdOn?: string;
    fromDate?: string;
    id?: number;
    interestRate?: number;
    isActive?: boolean;
    isDifferentialToBaseLendingRate?: boolean;
    modifiedBy?: string;
    modifiedOn?: string;
}

