/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FloatingRate } from './floatingRate';


export interface FloatingRatePeriod { 
    active?: boolean;
    createdBy: number;
    createdDate: string;
    differentialToBaseLendingRate?: boolean;
    floatingRate?: FloatingRate;
    fromDate?: string;
    id?: number;
    interestRate?: number;
    lastModifiedBy: number;
    lastModifiedDate: string;
    'new'?: boolean;
}

