/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FormDataContentDisposition { 
    creationDate?: string;
    fileName?: string;
    modificationDate?: string;
    name?: string;
    parameters?: { [key: string]: string; };
    readDate?: string;
    size?: number;
    type?: string;
}

