/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAccountTransfersStatus } from './getAccountTransfersStatus';
import { GetAccountTransfersTimeline } from './getAccountTransfersTimeline';


export interface GetAccountTransfersTemplateRefundByTransferFromClient { 
    accountNo?: number;
    activationDate?: string;
    active?: boolean;
    clientClassification?: object;
    clientType?: object;
    displayName?: string;
    firstname?: string;
    gender?: object;
    groups?: object;
    id?: number;
    lastname?: string;
    officeId?: number;
    officeName?: string;
    status?: GetAccountTransfersStatus;
    timeline?: GetAccountTransfersTimeline;
}

