/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAccountsChargeTimeType } from './getAccountsChargeTimeType';
import { GetAccountsChargesCurrency } from './getAccountsChargesCurrency';
import { GetAccountsChargeCalculationType } from './getAccountsChargeCalculationType';


export interface GetAccountsCharges { 
    accountId?: number;
    amount?: number;
    amountOrPercentage?: number;
    amountOutstanding?: number;
    amountPaid?: number;
    amountPercentageAppliedTo?: number;
    amountWaived?: number;
    amountWrittenOff?: number;
    chargeCalculationType?: GetAccountsChargeCalculationType;
    chargeId?: number;
    chargeTimeType?: GetAccountsChargeTimeType;
    currency?: GetAccountsChargesCurrency;
    id?: number;
    isActive?: boolean;
    name?: string;
    percentage?: number;
}

