/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetClientsColumnHeaderData } from './getClientsColumnHeaderData';


export interface GetClientsDataTables { 
    applicationTableName?: string;
    columnHeaderData?: Set<GetClientsColumnHeaderData>;
    registeredTableName?: string;
}

