/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetShareAccountsClientIdProductIdAccountingRule } from './getShareAccountsClientIdProductIdAccountingRule';
import { GetShareAccountsCurrency } from './getShareAccountsCurrency';
import { GetClientIdProductIdMinimumActivePeriodFrequencyTypeOptions } from './getClientIdProductIdMinimumActivePeriodFrequencyTypeOptions';
import { GetShareAccountsClientIdProductIdLockPeriodTypeEnum } from './getShareAccountsClientIdProductIdLockPeriodTypeEnum';
import { GetClientIdProductIdAccountingMappings } from './getClientIdProductIdAccountingMappings';
import { GetShareAccountsChargeOptions } from './getShareAccountsChargeOptions';
import { GetClientIdProductIdLockinPeriodFrequencyTypeOptions } from './getClientIdProductIdLockinPeriodFrequencyTypeOptions';
import { GetShareAccountsClientIdProductIdMinimumActivePeriodForDividendsTypeEnum } from './getShareAccountsClientIdProductIdMinimumActivePeriodForDividendsTypeEnum';


export interface GetClientIdProductIdProductOptions { 
    accountingMappingOptions?: object;
    accountingMappings?: GetClientIdProductIdAccountingMappings;
    accountingRule?: GetShareAccountsClientIdProductIdAccountingRule;
    allowDividendCalculationForInactiveClients?: boolean;
    chargeOptions?: GetShareAccountsChargeOptions;
    charges?: string;
    currency?: GetShareAccountsCurrency;
    currencyOptions?: GetShareAccountsCurrency;
    description?: string;
    id?: number;
    lockinPeriod?: number;
    lockinPeriodEnum?: GetShareAccountsClientIdProductIdLockPeriodTypeEnum;
    lockinPeriodFrequencyTypeOptions?: GetClientIdProductIdLockinPeriodFrequencyTypeOptions;
    marketPrice?: string;
    maximumShares?: number;
    minimumActivePeriod?: number;
    minimumActivePeriodForDividendsTypeEnum?: GetShareAccountsClientIdProductIdMinimumActivePeriodForDividendsTypeEnum;
    minimumActivePeriodFrequencyTypeOptions?: GetClientIdProductIdMinimumActivePeriodFrequencyTypeOptions;
    minimumShares?: number;
    name?: string;
    norminalShares?: number;
    shareCapital?: number;
    shortName?: string;
    totalShares?: number;
    totalSharesIssued?: number;
    unitPrice?: number;
}

