/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetChargesAppliesToResponse } from './getChargesAppliesToResponse';
import { GetChargesPaymentModeResponse } from './getChargesPaymentModeResponse';
import { GetChargesCalculationTypeResponse } from './getChargesCalculationTypeResponse';
import { GetChargesTimeTypeResponse } from './getChargesTimeTypeResponse';
import { GetChargesCurrencyResponse } from './getChargesCurrencyResponse';


/**
 * GetChargesResponse
 */
export interface GetChargesResponse { 
    active?: boolean;
    amount?: number;
    chargeAppliesTo?: GetChargesAppliesToResponse;
    chargeCalculationType?: GetChargesCalculationTypeResponse;
    chargePaymentMode?: GetChargesPaymentModeResponse;
    chargeTimeType?: GetChargesTimeTypeResponse;
    currency?: GetChargesCurrencyResponse;
    id?: number;
    maxCap?: number;
    minCap?: number;
    name?: string;
    penalty?: boolean;
}

