/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetCentersTimeline } from './getCentersTimeline';
import { GetCentersCenterIdCurrency } from './getCentersCenterIdCurrency';
import { GetCentersAccountType } from './getCentersAccountType';
import { GetCentersCenterIdStatus } from './getCentersCenterIdStatus';
import { GetCentersDepositType } from './getCentersDepositType';


export interface GetCentersSavingsAccounts { 
    accountNo?: number;
    accountType?: GetCentersAccountType;
    currency?: GetCentersCenterIdCurrency;
    depositType?: GetCentersDepositType;
    id?: number;
    productId?: number;
    productName?: string;
    status?: GetCentersCenterIdStatus;
    timeline?: GetCentersTimeline;
}

