/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetShareAccountsIncomeFromFeeAccountId } from './getShareAccountsIncomeFromFeeAccountId';
import { GetShareAccountsShareReferenceId } from './getShareAccountsShareReferenceId';
import { GetShareAccountsShareEquityId } from './getShareAccountsShareEquityId';
import { GetShareAccountsShareSuspenseId } from './getShareAccountsShareSuspenseId';


export interface GetClientIdProductIdAccountingMappings { 
    ShareEquityId?: GetShareAccountsShareEquityId;
    incomeFromFeeAccountId?: GetShareAccountsIncomeFromFeeAccountId;
    shareReferenceId?: GetShareAccountsShareReferenceId;
    shareSuspenseId?: GetShareAccountsShareSuspenseId;
}

