/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetClientsLoanAccountsType } from './getClientsLoanAccountsType';
import { GetClientsLoanAccountsStatus } from './getClientsLoanAccountsStatus';
import { GetClientsLoansAccountsCurrency } from './getClientsLoansAccountsCurrency';


export interface GetClientsLoanAccounts { 
    accountNo?: string;
    currency?: GetClientsLoansAccountsCurrency;
    externalId?: string;
    id?: number;
    loanCycle?: number;
    loanType?: GetClientsLoanAccountsType;
    productId?: number;
    productName?: string;
    status?: GetClientsLoanAccountsStatus;
}

