/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetClientChargeCurrency } from './getClientChargeCurrency';
import { GetClientChargeTimeType } from './getClientChargeTimeType';
import { GetClientChargeCalculationType } from './getClientChargeCalculationType';


export interface GetClientsChargesPageItems { 
    amount?: number;
    amountOutstanding?: number;
    amountPaid?: number;
    amountWaived?: number;
    amountWrittenOff?: number;
    chargeCalculationType?: GetClientChargeCalculationType;
    chargeId?: number;
    chargeTimeType?: GetClientChargeTimeType;
    clientId?: number;
    currency?: GetClientChargeCurrency;
    dueDate?: string;
    id?: number;
    isActive?: boolean;
    isPaid?: boolean;
    isWaived?: boolean;
    name?: string;
    penalty?: boolean;
}

