/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


/**
 * GetEntityDatatableChecksResponse
 */
export interface GetEntityDatatableChecksResponse { 
    datatableName?: string;
    entity?: string;
    id?: number;
    order?: number;
    productId?: number;
    productName?: string;
    status?: EnumOptionData;
    systemDefined?: boolean;
}

