/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanProductData } from './loanProductData';
import { SavingsProductData } from './savingsProductData';


/**
 * GetEntityDatatableChecksTemplateResponse
 */
export interface GetEntityDatatableChecksTemplateResponse { 
    datatables?: Array<object>;
    entities?: Array<string>;
    loanProductDatas?: Array<LoanProductData>;
    savingsProductDatas?: Array<SavingsProductData>;
    statusClient?: Array<object>;
    statusGroup?: Array<object>;
    statusLoans?: Array<object>;
    statusSavings?: Array<object>;
}

