/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFixedDepositAccountsPeriodTypes } from './getFixedDepositAccountsPeriodTypes';
import { GetFixedDepositAccountsChartSlabs } from './getFixedDepositAccountsChartSlabs';


export interface GetFixedDepositAccountsAccountChart { 
    accountId?: number;
    accountNumber?: number;
    chartSlabs?: Set<GetFixedDepositAccountsChartSlabs>;
    fromDate?: string;
    id?: number;
    periodTypes?: Set<GetFixedDepositAccountsPeriodTypes>;
}

