/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFixedDepositAccountsAccountChart } from './getFixedDepositAccountsAccountChart';
import { GetFixedDepositAccountsInterestCompoundingPeriodType } from './getFixedDepositAccountsInterestCompoundingPeriodType';
import { GetFixedDepositAccountsInterestCalculationDaysInYearType } from './getFixedDepositAccountsInterestCalculationDaysInYearType';
import { GetFixedDepositAccountsMaxDepositTermType } from './getFixedDepositAccountsMaxDepositTermType';
import { GetFixedDepositAccountsDepositPeriodFrequency } from './getFixedDepositAccountsDepositPeriodFrequency';
import { GetFixedDepositAccountsInterestCalculationType } from './getFixedDepositAccountsInterestCalculationType';
import { GetFixedDepositAccountsInterestPostingPeriodType } from './getFixedDepositAccountsInterestPostingPeriodType';
import { GetFixedDepositAccountsStatus } from './getFixedDepositAccountsStatus';
import { GetFixedDepositAccountsMinDepositTermType } from './getFixedDepositAccountsMinDepositTermType';
import { GetFixedDepositAccountsAccountIdSummary } from './getFixedDepositAccountsAccountIdSummary';
import { GetFixedDepositAccountsAccountIdCurrency } from './getFixedDepositAccountsAccountIdCurrency';
import { GetFixedDepositAccountsTimeline } from './getFixedDepositAccountsTimeline';


/**
 * GetFixedDepositAccountsAccountIdResponse
 */
export interface GetFixedDepositAccountsAccountIdResponse { 
    accountChart?: GetFixedDepositAccountsAccountChart;
    accountNo?: number;
    clientId?: number;
    clientName?: string;
    currency?: GetFixedDepositAccountsAccountIdCurrency;
    depositAmount?: number;
    depositPeriod?: number;
    depositPeriodFrequency?: GetFixedDepositAccountsDepositPeriodFrequency;
    externalId?: string;
    fieldOfficerId?: number;
    id?: number;
    interestCalculationDaysInYearType?: GetFixedDepositAccountsInterestCalculationDaysInYearType;
    interestCalculationType?: GetFixedDepositAccountsInterestCalculationType;
    interestCompoundingPeriodType?: GetFixedDepositAccountsInterestCompoundingPeriodType;
    interestFreePeriodApplicable?: boolean;
    interestPostingPeriodType?: GetFixedDepositAccountsInterestPostingPeriodType;
    maturityAmount?: number;
    maturityDate?: string;
    maxDepositTerm?: number;
    maxDepositTermType?: GetFixedDepositAccountsMaxDepositTermType;
    minDepositTerm?: number;
    minDepositTermType?: GetFixedDepositAccountsMinDepositTermType;
    preClosurePenalApplicable?: boolean;
    savingsProductId?: number;
    savingsProductName?: string;
    status?: GetFixedDepositAccountsStatus;
    summary?: GetFixedDepositAccountsAccountIdSummary;
    timeline?: GetFixedDepositAccountsTimeline;
}

