/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFixedDepositAccountsPeriodType } from './getFixedDepositAccountsPeriodType';
import { GetFixedDepositAccountsAccountChartCurrency } from './getFixedDepositAccountsAccountChartCurrency';


export interface GetFixedDepositAccountsChartSlabs { 
    annualInterestRate?: number;
    currency?: GetFixedDepositAccountsAccountChartCurrency;
    fromPeriod?: number;
    id?: number;
    periodType?: GetFixedDepositAccountsPeriodType;
    toPeriod?: number;
}

