/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetFixedDepositProductsProductIdChartSlabs } from './getFixedDepositProductsProductIdChartSlabs';
import { GetFixedDepositProductsProductIdPeriodType } from './getFixedDepositProductsProductIdPeriodType';


export interface GetFixedDepositProductsProductIdActiveChart { 
    chartSlabs?: Set<GetFixedDepositProductsProductIdChartSlabs>;
    fromDate?: string;
    id?: number;
    periodTypes?: Set<GetFixedDepositProductsProductIdPeriodType>;
    savingsProductId?: number;
    savingsProductName?: string;
}

