/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeValueData } from './codeValueData';
import { EnumOptionData } from './enumOptionData';


/**
 * GetGLAccountsResponse
 */
export interface GetGLAccountsResponse { 
    description?: string;
    disabled?: boolean;
    glCode?: string;
    id?: number;
    manualEntriesAllowed?: boolean;
    name?: string;
    nameDecorated?: string;
    organizationRunningBalance?: number;
    parentId?: number;
    tagId?: CodeValueData;
    type?: EnumOptionData;
    usage?: EnumOptionData;
}

