/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetGroupsStatus } from './getGroupsStatus';


export interface GetGroupsPageItems { 
    active?: boolean;
    hierarchy?: string;
    id?: number;
    name?: string;
    officeId?: number;
    officeName?: string;
    status?: GetGroupsStatus;
}

