/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GLAccountData } from './gLAccountData';
import { CodeValueData } from './codeValueData';
import { EnumOptionData } from './enumOptionData';


/**
 * GetGLAccountsTemplateResponse
 */
export interface GetGLAccountsTemplateResponse { 
    accountTypeOptions?: Array<EnumOptionData>;
    allowedAssetsTagOptions?: Array<CodeValueData>;
    allowedEquityTagOptions?: Array<CodeValueData>;
    allowedExpensesTagOptions?: Array<CodeValueData>;
    allowedIncomeTagOptions?: Array<CodeValueData>;
    allowedLiabilitiesTagOptions?: Array<CodeValueData>;
    assetHeaderAccountOptions?: Array<GLAccountData>;
    disabled?: boolean;
    equityHeaderAccountOptions?: Array<GLAccountData>;
    expenseHeaderAccountOptions?: Array<GLAccountData>;
    liabilityHeaderAccountOptions?: Array<GLAccountData>;
    manualEntriesAllowed?: boolean;
    type?: EnumOptionData;
    usage?: EnumOptionData;
    usageOptions?: Array<EnumOptionData>;
}

