/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetGroupsGroupIdAccountsSavingAccounts } from './getGroupsGroupIdAccountsSavingAccounts';
import { GetGroupsGroupIdAccountsLoanAccounts } from './getGroupsGroupIdAccountsLoanAccounts';
import { GetGroupsGroupIdAccountsMemberSavingsAccounts } from './getGroupsGroupIdAccountsMemberSavingsAccounts';
import { GetGroupsGroupIdAccountsMemberLoanAccounts } from './getGroupsGroupIdAccountsMemberLoanAccounts';


/**
 * GetGroupsGroupIdAccountsResponse
 */
export interface GetGroupsGroupIdAccountsResponse { 
    loanAccounts?: Set<GetGroupsGroupIdAccountsLoanAccounts>;
    memberLoanAccounts?: Set<GetGroupsGroupIdAccountsMemberLoanAccounts>;
    memberSavingsAccounts?: Set<GetGroupsGroupIdAccountsMemberSavingsAccounts>;
    savingsAccounts?: Set<GetGroupsGroupIdAccountsSavingAccounts>;
}

