/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


/**
 * GetHolidaysResponse
 */
export interface GetHolidaysResponse { 
    fromDate?: string;
    id?: number;
    name?: string;
    officeId?: number;
    repaymentsRescheduledTo?: string;
    status?: EnumOptionData;
    toDate?: string;
}

