/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JournalEntryTransactionItem } from './journalEntryTransactionItem';


/**
 * GetJournalEntriesTransactionIdResponse
 */
export interface GetJournalEntriesTransactionIdResponse { 
    pageItems?: Array<JournalEntryTransactionItem>;
    totalFilteredRecords?: number;
}

