/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoansLoanIdRepaymentPeriod } from './getLoansLoanIdRepaymentPeriod';
import { GetLoansLoanIdCurrency } from './getLoansLoanIdCurrency';


export interface GetLoansLoanIdRepaymentSchedule { 
    currency?: GetLoansLoanIdCurrency;
    loanTermInDays?: number;
    periods?: Array<GetLoansLoanIdRepaymentPeriod>;
    totalFeeChargesCharged?: number;
    totalInterestCharged?: number;
    totalOutstanding?: number;
    totalPaidInAdvance?: number;
    totalPaidLate?: number;
    totalPenaltyChargesCharged?: number;
    totalPrincipalDisbursed?: number;
    totalPrincipalExpected?: number;
    totalPrincipalPaid?: number;
    totalRepaymentExpected?: number;
    totalWaived?: number;
    totalWrittenOff?: number;
}

