/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoanProductsChargeOffReasonOptions } from './getLoanProductsChargeOffReasonOptions';
import { GetLoanCurrency } from './getLoanCurrency';
import { GetPaymentTypeOptions } from './getPaymentTypeOptions';
import { GetLoansTransactionType } from './getLoansTransactionType';
import { GetLoansTotal } from './getLoansTotal';


/**
 * GetLoansLoanIdTransactionsTemplateResponse
 */
export interface GetLoansLoanIdTransactionsTemplateResponse { 
    amount?: number;
    chargeOffReasonOptions?: Array<GetLoanProductsChargeOffReasonOptions>;
    currency?: GetLoanCurrency;
    date?: string;
    feeChargesPortion?: number;
    interestPortion?: number;
    netDisbursalAmount?: number;
    paymentTypeOptions?: Array<GetPaymentTypeOptions>;
    penaltyChargesPortion?: number;
    principalPortion?: number;
    total?: GetLoansTotal;
    type?: GetLoansTransactionType;
}

