/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetGlAccountMapping } from './getGlAccountMapping';


export interface GetLoanAccountingMappings { 
    chargeOffExpenseAccount?: GetGlAccountMapping;
    chargeOffFraudExpenseAccount?: GetGlAccountMapping;
    deferredIncomeLiabilityAccount?: GetGlAccountMapping;
    fundSourceAccount?: GetGlAccountMapping;
    goodwillCreditAccount?: GetGlAccountMapping;
    incomeFromCapitalizationAccount?: GetGlAccountMapping;
    incomeFromChargeOffFeesAccount?: GetGlAccountMapping;
    incomeFromChargeOffInterestAccount?: GetGlAccountMapping;
    incomeFromChargeOffPenaltyAccount?: GetGlAccountMapping;
    incomeFromFeeAccount?: GetGlAccountMapping;
    incomeFromGoodwillCreditFeesAccount?: GetGlAccountMapping;
    incomeFromGoodwillCreditInterestAccount?: GetGlAccountMapping;
    incomeFromGoodwillCreditPenaltyAccount?: GetGlAccountMapping;
    incomeFromPenaltyAccount?: GetGlAccountMapping;
    incomeFromRecoveryAccount?: GetGlAccountMapping;
    interestOnLoanAccount?: GetGlAccountMapping;
    loanPortfolioAccount?: GetGlAccountMapping;
    overpaymentLiabilityAccount?: GetGlAccountMapping;
    receivableFeeAccount?: GetGlAccountMapping;
    receivableInterestAccount?: GetGlAccountMapping;
    receivablePenaltyAccount?: GetGlAccountMapping;
    transfersInSuspenseAccount?: GetGlAccountMapping;
    writeOffAccount?: GetGlAccountMapping;
}

