/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoanProductsIncomeAccountOptions } from './getLoanProductsIncomeAccountOptions';
import { GetLoanProductsLiabilityAccountOptions } from './getLoanProductsLiabilityAccountOptions';
import { GetLoanProductsExpenseAccountOptions } from './getLoanProductsExpenseAccountOptions';
import { GetLoanProductsAssetAccountOptions } from './getLoanProductsAssetAccountOptions';


export interface GetLoanProductsAccountingMappingOptions { 
    assetAccountOptions?: Set<GetLoanProductsAssetAccountOptions>;
    expenseAccountOptions?: Set<GetLoanProductsExpenseAccountOptions>;
    incomeAccountOptions?: Set<GetLoanProductsIncomeAccountOptions>;
    liabilityAccountOptions?: Set<GetLoanProductsLiabilityAccountOptions>;
}

