/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoanChargeCalculationType } from './getLoanChargeCalculationType';
import { GetLoanProductsChargeAppliesTo } from './getLoanProductsChargeAppliesTo';
import { GetLoanProductsCurrencyOptions } from './getLoanProductsCurrencyOptions';
import { GetLoansChargePaymentMode } from './getLoansChargePaymentMode';
import { GetLoanChargeTimeType } from './getLoanChargeTimeType';


export interface GetLoanProductsChargeOptions { 
    active?: boolean;
    amount?: number;
    chargeAppliesTo?: GetLoanProductsChargeAppliesTo;
    chargeCalculationType?: GetLoanChargeCalculationType;
    chargePaymentMode?: GetLoansChargePaymentMode;
    chargeTimeType?: GetLoanChargeTimeType;
    currency?: GetLoanProductsCurrencyOptions;
    id?: number;
    name?: string;
    penalty?: boolean;
}

