/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoanChargeCalculationType } from './getLoanChargeCalculationType';
import { GetLoanChargeTemplateChargeTimeType } from './getLoanChargeTemplateChargeTimeType';
import { GetLoanChargeCurrency } from './getLoanChargeCurrency';
import { GetLoanChargeTemplateChargeAppliesTo } from './getLoanChargeTemplateChargeAppliesTo';


export interface GetLoanChargeTemplateChargeOptions { 
    active?: boolean;
    amount?: number;
    chargeAppliesTo?: GetLoanChargeTemplateChargeAppliesTo;
    chargeCalculationType?: GetLoanChargeCalculationType;
    chargeTimeType?: GetLoanChargeTemplateChargeTimeType;
    currency?: GetLoanChargeCurrency;
    id?: number;
    name?: string;
    penalty?: boolean;
}

