/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum option data
 */
export interface GetLoansLoanIdLoanTermEnumData { 
    code?: string;
    id?: number;
    value?: string;
}

