/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetLoansLoanIdDisbursementDetails { 
    actualDisbursementDate?: string;
    approvedPrincipal?: number;
    chargeAmount?: number;
    dateFormat?: string;
    expectedDisbursementDate?: string;
    id?: number;
    loanChargeId?: string;
    locale?: string;
    netDisbursalAmount?: number;
    note?: string;
    principal?: number;
    waivedChargeAmount?: number;
}

