/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetLoansTotal { 
    amount?: number;
    currencyCode?: string;
    defaultName?: string;
    digitsAfterDecimal?: number;
    displaySymbol?: string;
    displaySymbolValue?: string;
    greaterThanZero?: boolean;
    inMultiplesOf?: number;
    nameCode?: string;
    zero?: boolean;
}

