/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoanCurrency } from './getLoanCurrency';


/**
 * GetLoansApprovalTemplateResponse
 */
export interface GetLoansApprovalTemplateResponse { 
    approvalAmount?: number;
    approvalDate?: string;
    currency?: GetLoanCurrency;
    netDisbursalAmount?: number;
}

