/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetLoanProductsLiabilityUsage } from './getLoanProductsLiabilityUsage';
import { GetLoanProductsLiabilityTagId } from './getLoanProductsLiabilityTagId';
import { GetLoanProductsIncomeType } from './getLoanProductsIncomeType';


export interface GetLoanProductsIncomeAccountOptions { 
    disabled?: boolean;
    glCode?: string;
    id?: number;
    manualEntriesAllowed?: boolean;
    name?: string;
    nameDecorated?: string;
    organizationRunningBalance?: number;
    tagId?: GetLoanProductsLiabilityTagId;
    type?: GetLoanProductsIncomeType;
    usage?: GetLoanProductsLiabilityUsage;
}

