/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetNotification { 
    action?: string;
    actorId?: number;
    content?: string;
    createdAt?: string;
    id?: number;
    isRead?: boolean;
    isSystemGenerated?: boolean;
    objectId?: number;
    objectType?: string;
    officeId?: number;
    tenantIdentifier?: string;
    userIds?: Array<number>;
}

