/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetNotification } from './getNotification';


/**
 * GetNotificationsResponse
 */
export interface GetNotificationsResponse { 
    pageItems?: Array<GetNotification>;
    totalFilteredRecords?: number;
}

