/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetChargeAppliesTo } from './getChargeAppliesTo';
import { GetChargeTimeType } from './getChargeTimeType';
import { GetChargesCurrency } from './getChargesCurrency';
import { GetChargePaymentMode } from './getChargePaymentMode';
import { GetChargeCalculationType } from './getChargeCalculationType';


export interface GetProductsCharges { 
    active?: boolean;
    amount?: number;
    chargeAppliesTo?: GetChargeAppliesTo;
    chargeCalculationType?: GetChargeCalculationType;
    chargePaymentMode?: GetChargePaymentMode;
    chargeTimeType?: GetChargeTimeType;
    currency?: GetChargesCurrency;
    id?: number;
    name?: string;
    penalty?: boolean;
}

