/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * GetPasswordPreferencesTemplateResponse
 */
export interface GetPasswordPreferencesTemplateResponse { 
    active?: boolean;
    description?: string;
    id?: number;
    key?: string;
}

