/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * GetProvisioningCriteriaResponse
 */
export interface GetProvisioningCriteriaResponse { 
    createdBy?: string;
    criteriaId?: number;
    criteriaName?: string;
}

