/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetProductsPageItems } from './getProductsPageItems';


/**
 * GetProductsTypeResponse
 */
export interface GetProductsTypeResponse { 
    pageItems?: Set<GetProductsPageItems>;
    totalFilteredRecords?: number;
}

