/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetProductsLiabilityAccountOptions } from './getProductsLiabilityAccountOptions';
import { GetProductsIncomeAccountOptions } from './getProductsIncomeAccountOptions';
import { GetProductsEquityAccountOptions } from './getProductsEquityAccountOptions';
import { GetProductsAssetAccountOptions } from './getProductsAssetAccountOptions';


export interface GetProductsAccountingMappingOptions { 
    assetAccountOptions?: Set<GetProductsAssetAccountOptions>;
    equityAccountOptions?: Set<GetProductsEquityAccountOptions>;
    incomeAccountOptions?: Set<GetProductsIncomeAccountOptions>;
    liabilityAccountOptions?: Set<GetProductsLiabilityAccountOptions>;
}

