/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetProductsLiabilityUsage } from './getProductsLiabilityUsage';
import { GetIncomeType } from './getIncomeType';
import { GetProductsTagId } from './getProductsTagId';


export interface GetProductsIncomeAccountOptions { 
    description?: string;
    disabled?: boolean;
    glCode?: string;
    id?: number;
    manualEntriesAllowed?: boolean;
    name?: string;
    nameDecorated?: string;
    tagId?: GetProductsTagId;
    type?: GetIncomeType;
    usage?: GetProductsLiabilityUsage;
}

