/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRecurringDepositAccountsMaxDepositTermType } from './getRecurringDepositAccountsMaxDepositTermType';
import { GetRecurringDepositAccountsSummary } from './getRecurringDepositAccountsSummary';
import { GetRecurringDepositAccountsInterestCalculationType } from './getRecurringDepositAccountsInterestCalculationType';
import { GetRecurringDepositAccountsMinDepositTermType } from './getRecurringDepositAccountsMinDepositTermType';
import { GetRecurringDepositAccountsDepositPeriodFrequency } from './getRecurringDepositAccountsDepositPeriodFrequency';
import { GetRecurringDepositAccountsRecurringDepositFrequencyType } from './getRecurringDepositAccountsRecurringDepositFrequencyType';
import { GetRecurringDepositAccountsStatus } from './getRecurringDepositAccountsStatus';
import { GetRecurringDepositAccountsCurrency } from './getRecurringDepositAccountsCurrency';
import { GetRecurringDepositAccountsInterestPostingPeriodType } from './getRecurringDepositAccountsInterestPostingPeriodType';
import { GetRecurringDepositAccountsInterestCalculationDaysInYearType } from './getRecurringDepositAccountsInterestCalculationDaysInYearType';
import { GetRecurringDepositAccountsTimeline } from './getRecurringDepositAccountsTimeline';
import { GetRecurringDepositAccountsInterestCompoundingPeriodType } from './getRecurringDepositAccountsInterestCompoundingPeriodType';


/**
 * GetRecurringDepositAccountsResponse
 */
export interface GetRecurringDepositAccountsResponse { 
    accountNo?: number;
    clientId?: number;
    clientName?: string;
    currency?: GetRecurringDepositAccountsCurrency;
    depositAmount?: number;
    depositPeriod?: number;
    depositPeriodFrequency?: GetRecurringDepositAccountsDepositPeriodFrequency;
    fieldOfficerId?: number;
    id?: number;
    interestCalculationDaysInYearType?: GetRecurringDepositAccountsInterestCalculationDaysInYearType;
    interestCalculationType?: GetRecurringDepositAccountsInterestCalculationType;
    interestCompoundingPeriodType?: GetRecurringDepositAccountsInterestCompoundingPeriodType;
    interestPostingPeriodType?: GetRecurringDepositAccountsInterestPostingPeriodType;
    maturityAmount?: number;
    maturityDate?: string;
    maxDepositTerm?: number;
    maxDepositTermType?: GetRecurringDepositAccountsMaxDepositTermType;
    minDepositTerm?: number;
    minDepositTermType?: GetRecurringDepositAccountsMinDepositTermType;
    preClosurePenalApplicable?: boolean;
    recurringDepositAmount?: number;
    recurringDepositFrequency?: number;
    recurringDepositFrequencyType?: GetRecurringDepositAccountsRecurringDepositFrequencyType;
    savingsProductId?: number;
    savingsProductName?: string;
    status?: GetRecurringDepositAccountsStatus;
    summary?: GetRecurringDepositAccountsSummary;
    timeline?: GetRecurringDepositAccountsTimeline;
}

