/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRecurringDepositProductsGlAccount } from './getRecurringDepositProductsGlAccount';


export interface GetRecurringDepositProductsProductIdAccountingMappings { 
    feeReceivableAccount?: GetRecurringDepositProductsGlAccount;
    incomeFromFeeAccount?: GetRecurringDepositProductsGlAccount;
    incomeFromPenaltyAccount?: GetRecurringDepositProductsGlAccount;
    interestOnSavingsAccount?: GetRecurringDepositProductsGlAccount;
    interestPayableAccount?: GetRecurringDepositProductsGlAccount;
    penaltyReceivableAccount?: GetRecurringDepositProductsGlAccount;
    savingsControlAccount?: GetRecurringDepositProductsGlAccount;
    transfersInSuspenseAccount?: GetRecurringDepositProductsGlAccount;
}

