/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRecurringDepositProductsProductIdChartSlabs } from './getRecurringDepositProductsProductIdChartSlabs';
import { GetRecurringDepositProductsProductIdPeriodType } from './getRecurringDepositProductsProductIdPeriodType';


export interface GetRecurringDepositProductsProductIdActiveChart { 
    chartSlabs?: Set<GetRecurringDepositProductsProductIdChartSlabs>;
    fromDate?: string;
    id?: number;
    periodTypes?: Set<GetRecurringDepositProductsProductIdPeriodType>;
    savingsProductId?: number;
    savingsProductName?: string;
}

