/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetRecurringDepositProductsProductIdPeriodType } from './getRecurringDepositProductsProductIdPeriodType';
import { GetRecurringDepositProductsProductIdCurrency } from './getRecurringDepositProductsProductIdCurrency';


export interface GetRecurringDepositProductsProductIdChartSlabs { 
    annualInterestRate?: number;
    currency?: GetRecurringDepositProductsProductIdCurrency;
    description?: string;
    fromPeriod?: number;
    id?: number;
    periodType?: GetRecurringDepositProductsProductIdPeriodType;
    toPeriod?: number;
}

