/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * GetReportsResponse
 */
export interface GetReportsResponse { 
    coreReport?: boolean;
    description?: string;
    id?: number;
    reportCategory?: string;
    reportName?: string;
    reportParameters?: Array<object>;
    reportSql?: string;
    reportSubType?: string;
    reportType?: string;
    useReport?: boolean;
}

