/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSelfSavingsChargeTimeType } from './getSelfSavingsChargeTimeType';
import { GetSelfSavingsCurrency } from './getSelfSavingsCurrency';
import { GetSelfSavingsChargeCalculationType } from './getSelfSavingsChargeCalculationType';


/**
 * GetSelfSavingsAccountsAccountIdChargesResponse
 */
export interface GetSelfSavingsAccountsAccountIdChargesResponse { 
    accountId?: number;
    amount?: number;
    amountOrPercentage?: number;
    amountOutstanding?: number;
    amountPaid?: number;
    amountPercentageAppliedTo?: number;
    amountWaived?: number;
    amountWrittenOff?: number;
    chargeCalculationType?: GetSelfSavingsChargeCalculationType;
    chargeId?: number;
    chargeTimeType?: GetSelfSavingsChargeTimeType;
    currency?: GetSelfSavingsCurrency;
    id?: number;
    name?: string;
    penalty?: boolean;
    percentage?: number;
}

