/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSavingsProductsLiabilityUsage } from './getSavingsProductsLiabilityUsage';
import { GetSavingsProductsExpenseType } from './getSavingsProductsExpenseType';


export interface GetSavingsProductsExpenseAccountOptions { 
    disabled?: boolean;
    glCode?: string;
    id?: number;
    manualEntriesAllowed?: boolean;
    name?: string;
    tagId?: object;
    type?: GetSavingsProductsExpenseType;
    usage?: GetSavingsProductsLiabilityUsage;
}

