/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetClientIdProductIdChargeOptions } from './getClientIdProductIdChargeOptions';
import { GetClientIdProductIdProductOptions } from './getClientIdProductIdProductOptions';


/**
 * GetShareAccountsClientIdProductIdResponse
 */
export interface GetShareAccountsClientIdProductIdResponse { 
    chargeOptions?: Set<GetClientIdProductIdChargeOptions>;
    productOptions?: Set<GetClientIdProductIdProductOptions>;
}

