/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSelfSavingsPaymentType } from './getSelfSavingsPaymentType';


export interface GetSelfSavingsPaymentDetailData { 
    accountNumber?: number;
    bankNumber?: number;
    checkNumber?: number;
    id?: number;
    paymentType?: GetSelfSavingsPaymentType;
    receiptNumber?: number;
    routingCode?: number;
}

