/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetTransactionsCurrency } from './getTransactionsCurrency';
import { GetTranscationEnumData } from './getTranscationEnumData';
import { GetTransactionsPaymentDetailData } from './getTransactionsPaymentDetailData';
import { GetSavingsAccountChargesPaidByData } from './getSavingsAccountChargesPaidByData';


export interface GetSavingsAccountTransactionsPageItem { 
    accountId?: number;
    accountNo?: string;
    amount?: number;
    chargesPaidByData?: Set<GetSavingsAccountChargesPaidByData>;
    currency?: GetTransactionsCurrency;
    date?: string;
    entryType?: GetSavingsAccountTransactionsPageItem.EntryTypeEnum;
    id?: number;
    interestedPostedAsOn?: boolean;
    isManualTransaction?: boolean;
    isReversal?: boolean;
    lienTransaction?: boolean;
    originalTransactionId?: number;
    paymentDetailData?: GetTransactionsPaymentDetailData;
    releaseTransactionId?: number;
    reversed?: boolean;
    runningBalance?: number;
    submittedByUsername?: string;
    submittedOnDate?: string;
    transactionType?: GetTranscationEnumData;
}
export namespace GetSavingsAccountTransactionsPageItem {
    export const EntryTypeEnum = {
        Credit: 'CREDIT',
        Debit: 'DEBIT'
    } as const;
    export type EntryTypeEnum = typeof EntryTypeEnum[keyof typeof EntryTypeEnum];
}


