/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSavingsProductsInterestCalculationDaysInYearType } from './getSavingsProductsInterestCalculationDaysInYearType';
import { GetSavingsProductsPaymentChannelToFundSourceMappings } from './getSavingsProductsPaymentChannelToFundSourceMappings';
import { GetSavingsProductsInterestCalculationType } from './getSavingsProductsInterestCalculationType';
import { GetSavingsCurrency } from './getSavingsCurrency';
import { GetSavingsProductsFeeToIncomeAccountMappings } from './getSavingsProductsFeeToIncomeAccountMappings';
import { GetSavingsProductsInterestCompoundingPeriodType } from './getSavingsProductsInterestCompoundingPeriodType';
import { GetSavingsProductsAccountingMappings } from './getSavingsProductsAccountingMappings';
import { GetSavingsProductsInterestPostingPeriodType } from './getSavingsProductsInterestPostingPeriodType';
import { GetSavingsProductsPenaltyToIncomeAccountMappings } from './getSavingsProductsPenaltyToIncomeAccountMappings';
import { GetSavingsProductsAccountingRule } from './getSavingsProductsAccountingRule';


/**
 * GetSavingsProductsProductIdResponse
 */
export interface GetSavingsProductsProductIdResponse { 
    accountingMappings?: GetSavingsProductsAccountingMappings;
    accountingRule?: GetSavingsProductsAccountingRule;
    charges?: Array<number>;
    currency?: GetSavingsCurrency;
    description?: string;
    feeToIncomeAccountMappings?: Set<GetSavingsProductsFeeToIncomeAccountMappings>;
    id?: number;
    interestCalculationDaysInYearType?: GetSavingsProductsInterestCalculationDaysInYearType;
    interestCalculationType?: GetSavingsProductsInterestCalculationType;
    interestCompoundingPeriodType?: GetSavingsProductsInterestCompoundingPeriodType;
    interestPostingPeriodType?: GetSavingsProductsInterestPostingPeriodType;
    name?: string;
    nominalAnnualInterestRate?: number;
    paymentChannelToFundSourceMappings?: Set<GetSavingsProductsPaymentChannelToFundSourceMappings>;
    penaltyToIncomeAccountMappings?: Set<GetSavingsProductsPenaltyToIncomeAccountMappings>;
    shortName?: string;
    withdrawalFeeForTransfers?: boolean;
}

