/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSelfClientsSavingsAccountsCurrency } from './getSelfClientsSavingsAccountsCurrency';
import { GetSelfClientsSavingsAccountsStatus } from './getSelfClientsSavingsAccountsStatus';


export interface GetSelfClientsSavingsAccounts { 
    accountNo?: number;
    currency?: GetSelfClientsSavingsAccountsCurrency;
    id?: number;
    productId?: number;
    productName?: string;
    status?: GetSelfClientsSavingsAccountsStatus;
}

