/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSelfClientsLoanAccountsStatus } from './getSelfClientsLoanAccountsStatus';
import { GetSelfClientsLoanAccountsType } from './getSelfClientsLoanAccountsType';


export interface GetSelfClientsLoanAccounts { 
    accountNo?: number;
    externalId?: string;
    id?: number;
    loanCycle?: number;
    loanType?: GetSelfClientsLoanAccountsType;
    productId?: number;
    productName?: string;
    status?: GetSelfClientsLoanAccountsStatus;
}

