/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSavingsProductsInterestCalculationDaysInYearType } from './getSavingsProductsInterestCalculationDaysInYearType';
import { GetSavingsProductsInterestCalculationType } from './getSavingsProductsInterestCalculationType';
import { GetSavingsCurrency } from './getSavingsCurrency';
import { GetSavingsProductsInterestCompoundingPeriodType } from './getSavingsProductsInterestCompoundingPeriodType';
import { GetSavingsProductsInterestPostingPeriodType } from './getSavingsProductsInterestPostingPeriodType';
import { GetSavingsProductsAccountingRule } from './getSavingsProductsAccountingRule';


/**
 * GetSavingsProductsResponse
 */
export interface GetSavingsProductsResponse { 
    accountingRule?: GetSavingsProductsAccountingRule;
    currency?: GetSavingsCurrency;
    description?: string;
    id?: number;
    interestCalculationDaysInYearType?: GetSavingsProductsInterestCalculationDaysInYearType;
    interestCalculationType?: GetSavingsProductsInterestCalculationType;
    interestCompoundingPeriodType?: GetSavingsProductsInterestCompoundingPeriodType;
    interestPostingPeriodType?: GetSavingsProductsInterestPostingPeriodType;
    name?: string;
    nominalAnnualInterestRate?: number;
    shortName?: string;
    withdrawalFeeForTransfers?: boolean;
}

