/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSavingsProductsPaymentType } from './getSavingsProductsPaymentType';
import { GetSavingsProductsFundSourceAccount } from './getSavingsProductsFundSourceAccount';


export interface GetSavingsProductsPaymentChannelToFundSourceMappings { 
    fundSourceAccount?: GetSavingsProductsFundSourceAccount;
    paymentType?: GetSavingsProductsPaymentType;
}

