/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


/**
 * GetSearchResponse
 */
export interface GetSearchResponse { 
    entityAccountNo?: number;
    entityExternalId?: string;
    entityId?: number;
    entityName?: string;
    entityStatus?: EnumOptionData;
    entityType?: string;
    parentId?: number;
    parentName?: string;
}

