/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSelfClientsTimeline } from './getSelfClientsTimeline';
import { GetSelfClientsStatus } from './getSelfClientsStatus';


/**
 * GetSelfClientsClientIdResponse
 */
export interface GetSelfClientsClientIdResponse { 
    accountNo?: number;
    activationDate?: string;
    active?: boolean;
    displayName?: string;
    firstname?: string;
    groups?: Array<string>;
    id?: number;
    lastname?: string;
    officeId?: number;
    officeName?: string;
    savingsProductId?: number;
    savingsProductName?: string;
    status?: GetSelfClientsStatus;
    timeline?: GetSelfClientsTimeline;
}

