/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetTransferTypeOptionsResponseStandingInstructionSwagger } from './getTransferTypeOptionsResponseStandingInstructionSwagger';
import { GetRecurrenceFrequencyOptionsResponseStandingInstructionSwagger } from './getRecurrenceFrequencyOptionsResponseStandingInstructionSwagger';
import { GetStatusOptionsResponseStandingInstructionSwagger } from './getStatusOptionsResponseStandingInstructionSwagger';
import { GetFromAccountTypeOptionsResponseStandingInstructionSwagger } from './getFromAccountTypeOptionsResponseStandingInstructionSwagger';
import { GetToAccountTypeOptionsResponseStandingInstructionSwagger } from './getToAccountTypeOptionsResponseStandingInstructionSwagger';
import { GetFromAccountTypeResponseStandingInstructionSwagger } from './getFromAccountTypeResponseStandingInstructionSwagger';
import { GetToOfficeOptionsResponseStandingInstructionSwagger } from './getToOfficeOptionsResponseStandingInstructionSwagger';
import { GetInstructionTypeOptionsResponseStandingInstructionSwagger } from './getInstructionTypeOptionsResponseStandingInstructionSwagger';
import { GetFromClientOptionsResponseStandingInstructionSwagger } from './getFromClientOptionsResponseStandingInstructionSwagger';
import { GetRecurrenceTypeOptionsResponseStandingInstructionSwagger } from './getRecurrenceTypeOptionsResponseStandingInstructionSwagger';
import { GetFromOfficeResponseStandingInstructionSwagger } from './getFromOfficeResponseStandingInstructionSwagger';
import { GetFromOfficeOptionsResponseStandingInstructionSwagger } from './getFromOfficeOptionsResponseStandingInstructionSwagger';
import { GetPriorityOptionsResponseStandingInstructionSwagger } from './getPriorityOptionsResponseStandingInstructionSwagger';


/**
 * GetStandingInstructionsTemplateResponse
 */
export interface GetStandingInstructionsTemplateResponse { 
    fromAccountType?: GetFromAccountTypeResponseStandingInstructionSwagger;
    fromAccountTypeOptions?: Set<GetFromAccountTypeOptionsResponseStandingInstructionSwagger>;
    fromClientOptions?: Set<GetFromClientOptionsResponseStandingInstructionSwagger>;
    fromOffice?: GetFromOfficeResponseStandingInstructionSwagger;
    fromOfficeOptions?: Set<GetFromOfficeOptionsResponseStandingInstructionSwagger>;
    instructionTypeOptions?: Set<GetInstructionTypeOptionsResponseStandingInstructionSwagger>;
    priorityOptions?: Set<GetPriorityOptionsResponseStandingInstructionSwagger>;
    recurrenceFrequencyOptions?: Set<GetRecurrenceFrequencyOptionsResponseStandingInstructionSwagger>;
    recurrenceTypeOptions?: Set<GetRecurrenceTypeOptionsResponseStandingInstructionSwagger>;
    statusOptions?: Set<GetStatusOptionsResponseStandingInstructionSwagger>;
    toAccountTypeOptions?: Set<GetToAccountTypeOptionsResponseStandingInstructionSwagger>;
    toOfficeOptions?: Set<GetToOfficeOptionsResponseStandingInstructionSwagger>;
    transferTypeOptions?: Set<GetTransferTypeOptionsResponseStandingInstructionSwagger>;
}

