/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetSelfLoansLoanIdTransactionsType { 
    code?: string;
    contra?: boolean;
    description?: string;
    disbursement?: boolean;
    id?: number;
    recoveryRepayment?: boolean;
    repayment?: boolean;
    repaymentAtDisbursement?: boolean;
    waiveCharges?: boolean;
    waiveInterest?: boolean;
    writeOff?: boolean;
}

