/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * GetTellersTellerIdCashiersCashierIdResponse
 */
export interface GetTellersTellerIdCashiersCashierIdResponse { 
    description?: string;
    endDate?: string;
    endTime?: string;
    id?: number;
    isFullDay?: boolean;
    staffId?: number;
    staffName?: string;
    startDate?: string;
    startTime?: string;
    tellerId?: number;
    tellerName?: string;
}

