/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CashierTxnType } from './cashierTxnType';


/**
 * GetTellersTellerIdCashiersCashiersIdTransactionsResponse
 */
export interface GetTellersTellerIdCashiersCashiersIdTransactionsResponse { 
    cashierId?: number;
    cashierName?: string;
    createdDate?: string;
    entityId?: number;
    entityType?: string;
    id?: number;
    officeId?: number;
    officeName?: string;
    tellerId?: number;
    txnAmount?: number;
    txnDate?: string;
    txnNote?: string;
    txnType?: CashierTxnType;
}

