/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencyData } from './currencyData';
import { CashierData } from './cashierData';


/**
 * GetTellersTellerIdCashiersCashiersIdTransactionsTemplateResponse
 */
export interface GetTellersTellerIdCashiersCashiersIdTransactionsTemplateResponse { 
    cashierData?: CashierData;
    cashierId?: number;
    cashierName?: string;
    currencyOptions?: Array<CurrencyData>;
    endDate?: string;
    officeName?: string;
    startDate?: string;
    tellerId?: number;
    tellerName?: string;
}

