/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StaffData } from './staffData';
import { RoleData } from './roleData';


/**
 * GetUsersUserIdResponse
 */
export interface GetUsersUserIdResponse { 
    availableRoles?: Array<RoleData>;
    email?: string;
    firstname?: string;
    id?: number;
    lastname?: string;
    officeId?: number;
    officeName?: string;
    passwordNeverExpires?: boolean;
    selectedRoles?: Array<RoleData>;
    staff?: StaffData;
    username?: string;
}

