/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeValueData } from './codeValueData';
import { EnumOptionData } from './enumOptionData';


export interface GLAccountData { 
    accountTypeOptions?: Array<EnumOptionData>;
    allowedAssetsTagOptions?: Array<CodeValueData>;
    allowedEquityTagOptions?: Array<CodeValueData>;
    allowedExpensesTagOptions?: Array<CodeValueData>;
    allowedIncomeTagOptions?: Array<CodeValueData>;
    allowedLiabilitiesTagOptions?: Array<CodeValueData>;
    assetHeaderAccountOptions?: Array<GLAccountData>;
    description?: string;
    disabled?: boolean;
    equityHeaderAccountOptions?: Array<GLAccountData>;
    expenseHeaderAccountOptions?: Array<GLAccountData>;
    glCode?: string;
    id?: number;
    incomeHeaderAccountOptions?: Array<GLAccountData>;
    liabilityHeaderAccountOptions?: Array<GLAccountData>;
    manualEntriesAllowed?: boolean;
    name?: string;
    nameDecorated?: string;
    organizationRunningBalance?: number;
    parentId?: number;
    rowIndex?: number;
    tagId?: CodeValueData;
    type?: EnumOptionData;
    usage?: EnumOptionData;
    usageOptions?: Array<EnumOptionData>;
}

