/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeValue } from './codeValue';


export interface GLAccount { 
    children?: Array<GLAccount>;
    description?: string;
    detailAccount?: boolean;
    disabled?: boolean;
    glCode?: string;
    headerAccount?: boolean;
    hierarchy?: string;
    id?: number;
    manualEntriesAllowed?: boolean;
    name?: string;
    'new'?: boolean;
    parent?: GLAccount;
    tagId?: CodeValue;
    type?: number;
    usage?: number;
}

