/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfficeData } from './officeData';


export interface GLClosureData { 
    allowedOffices?: Array<OfficeData>;
    closingDate?: string;
    comments?: string;
    createdByUserId?: number;
    createdByUsername?: string;
    createdDate?: string;
    deleted?: boolean;
    id?: number;
    lastUpdatedByUserId?: number;
    lastUpdatedByUsername?: string;
    lastUpdatedDate?: string;
    officeId?: number;
    officeName?: string;
}

