/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GlobalConfigurationPropertyData { 
    dateValue?: string;
    description?: string;
    enabled?: boolean;
    id?: number;
    name?: string;
    stringValue?: string;
    trapDoor?: boolean;
    value?: number;
}

