/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DepositAccountOnHoldTransactionData } from './depositAccountOnHoldTransactionData';
import { LoanTransactionData } from './loanTransactionData';


export interface GuarantorTransactionData { 
    id?: number;
    loanTransactionData?: LoanTransactionData;
    onHoldTransactionData?: DepositAccountOnHoldTransactionData;
    reversed?: boolean;
}

