/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PortfolioAccountData } from './portfolioAccountData';
import { GuarantorTransactionData } from './guarantorTransactionData';
import { EnumOptionData } from './enumOptionData';


export interface GuarantorFundingData { 
    amount?: number;
    amountReleased?: number;
    amountRemaining?: number;
    amountTransfered?: number;
    guarantorTransactions?: Array<GuarantorTransactionData>;
    id?: number;
    savingsAccount?: PortfolioAccountData;
    status?: EnumOptionData;
}

