/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GuarantorsRequest { 
    addressLine1?: string;
    addressLine2?: string;
    amount?: number;
    city?: string;
    clientRelationshipTypeId?: number;
    comment?: string;
    country?: string;
    dateFormat?: string;
    dob?: string;
    entityId?: number;
    firstname?: string;
    guarantorTypeId?: number;
    housePhoneNumber?: string;
    lastname?: string;
    locale?: string;
    mobileNumber?: string;
    savingsId?: number;
    state?: string;
    zip?: string;
}

