/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostalAddress } from './postalAddress';
import { IdDocument } from './idDocument';
import { SubjectName } from './subjectName';
import { ExternalId } from './externalId';


export interface InteropKycResponseData { 
    birthCountry?: string;
    changes?: { [key: string]: object; };
    clientId?: number;
    commandId?: number;
    contactPhone?: string;
    creditBureauReportData?: { [key: string]: object; };
    dateOfBirth?: string;
    emailAddress?: string;
    externalIdOrNull?: ExternalId;
    gender?: string;
    glimId?: number;
    groupId?: number;
    gsimId?: number;
    idDocument?: Array<IdDocument>;
    loanExternalId?: ExternalId;
    loanId?: number;
    nationality?: string;
    officeId?: number;
    postalAddress?: PostalAddress;
    productId?: number;
    resourceExternalId?: ExternalId;
    resourceId?: number;
    resourceIdentifier?: string;
    rollbackTransaction?: boolean;
    savingsId?: number;
    subResourceExternalId?: ExternalId;
    subResourceId?: number;
    subjectName?: SubjectName;
    transactionId?: string;
}

