/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeoCodeData } from './geoCodeData';
import { MoneyData } from './moneyData';
import { InteropTransactionTypeData } from './interopTransactionTypeData';
import { ExtensionData } from './extensionData';


export interface InteropTransferRequestData { 
    accountId: string;
    amount: MoneyData;
    expiration?: string;
    expirationLocalDate?: string;
    extensionList?: Array<ExtensionData>;
    fspCommission?: MoneyData;
    fspFee?: MoneyData;
    geoCode?: GeoCodeData;
    note?: string;
    requestCode?: string;
    transactionCode: string;
    transactionRole: InteropTransferRequestData.TransactionRoleEnum;
    transactionType?: InteropTransactionTypeData;
    transferCode: string;
}
export namespace InteropTransferRequestData {
    export const TransactionRoleEnum = {
        Payer: 'PAYER',
        Payee: 'PAYEE'
    } as const;
    export type TransactionRoleEnum = typeof TransactionRoleEnum[keyof typeof TransactionRoleEnum];
}


