/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request DTO for creating an interest pause
 */
export interface InterestPauseRequestDto { 
    /**
     * Format of the dates provided
     */
    dateFormat?: string;
    /**
     * End date of the interest pause period
     */
    endDate?: string;
    /**
     * Locale to interpret the date format
     */
    locale?: string;
    /**
     * Start date of the interest pause period
     */
    startDate?: string;
}

