/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencyData } from './currencyData';
import { CodeValueData } from './codeValueData';
import { EnumOptionData } from './enumOptionData';


export interface InterestRateChartSlabData { 
    amountRangeFrom?: number;
    amountRangeTo?: number;
    annualInterestRate?: number;
    attributeNameOptions?: Array<EnumOptionData>;
    clientClassificationOptions?: Array<CodeValueData>;
    clientTypeOptions?: Array<CodeValueData>;
    conditionTypeOptions?: Array<EnumOptionData>;
    currency?: CurrencyData;
    description?: string;
    entityTypeOptions?: Array<EnumOptionData>;
    fromPeriod?: number;
    genderOptions?: Array<CodeValueData>;
    id?: number;
    incentiveTypeOptions?: Array<EnumOptionData>;
    incentives?: Set<object>;
    periodType?: EnumOptionData;
    periodTypes?: Array<EnumOptionData>;
    toPeriod?: number;
}

