/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InterestIncentiveRequest { 
    amount?: number;
    attributeName?: number;
    attributeValue?: string;
    conditionType?: number;
    description?: string;
    entityType?: number;
    id?: number;
    incentiveType?: number;
}

