/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MoneyData } from './moneyData';
import { ExternalId } from './externalId';
import { ExtensionData } from './extensionData';


export interface InteropQuoteResponseData { 
    changes?: { [key: string]: object; };
    clientId?: number;
    commandId?: number;
    creditBureauReportData?: { [key: string]: object; };
    expiration?: string;
    extensionList?: Array<ExtensionData>;
    externalIdOrNull?: ExternalId;
    fspCommission?: MoneyData;
    fspFee?: MoneyData;
    glimId?: number;
    groupId?: number;
    gsimId?: number;
    loanExternalId?: ExternalId;
    loanId?: number;
    officeId?: number;
    productId?: number;
    quoteCode: string;
    resourceExternalId?: ExternalId;
    resourceId?: number;
    resourceIdentifier?: string;
    rollbackTransaction?: boolean;
    savingsId?: number;
    state: InteropQuoteResponseData.StateEnum;
    subResourceExternalId?: ExternalId;
    subResourceId?: number;
    transactionCode: string;
    transactionId?: string;
}
export namespace InteropQuoteResponseData {
    export const StateEnum = {
        Accepted: 'ACCEPTED',
        Rejected: 'REJECTED'
    } as const;
    export type StateEnum = typeof StateEnum[keyof typeof StateEnum];
}


