/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Money } from './money';
import { RepaymentPeriod } from './repaymentPeriod';
import { InterestPeriodMc } from './interestPeriodMc';


export interface InterestPeriod { 
    balanceCorrectionAmount?: Money;
    calculatedDueInterest?: number;
    capitalizedIncomePrincipal?: Money;
    creditedAmounts?: Money;
    creditedInterest?: Money;
    creditedPrincipal?: Money;
    disbursementAmount?: Money;
    dueDate: string;
    firstInterestPeriod?: boolean;
    fromDate: string;
    length?: number;
    lengthTillPeriodDueDate?: number;
    mc?: InterestPeriodMc;
    outstandingLoanBalance?: Money;
    paused?: boolean;
    rateFactor?: number;
    rateFactorTillPeriodDueDate?: number;
    repaymentPeriod?: RepaymentPeriod;
}

