/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencyData } from './currencyData';


export interface LoanProductMinimumRepaymentScheduleRelatedDetail { 
    allowPartialPeriodInterestCalculation?: boolean;
    amortizationMethod?: LoanProductMinimumRepaymentScheduleRelatedDetail.AmortizationMethodEnum;
    annualNominalInterestRate?: number;
    currencyData?: CurrencyData;
    daysInMonthType?: number;
    daysInYearCustomStrategy?: LoanProductMinimumRepaymentScheduleRelatedDetail.DaysInYearCustomStrategyEnum;
    daysInYearType?: number;
    graceOnArrearsAgeing?: number;
    graceOnInterestCharged?: number;
    graceOnInterestPayment?: number;
    graceOnPrincipalPayment?: number;
    interestCalculationPeriodMethod?: LoanProductMinimumRepaymentScheduleRelatedDetail.InterestCalculationPeriodMethodEnum;
    interestMethod?: LoanProductMinimumRepaymentScheduleRelatedDetail.InterestMethodEnum;
    interestPeriodFrequencyType?: LoanProductMinimumRepaymentScheduleRelatedDetail.InterestPeriodFrequencyTypeEnum;
    interestRecognitionOnDisbursementDate?: boolean;
    nominalInterestRatePerPeriod?: number;
    numberOfRepayments?: number;
    recurringMoratoriumOnPrincipalPeriods?: number;
    repayEvery?: number;
    repaymentPeriodFrequencyType?: LoanProductMinimumRepaymentScheduleRelatedDetail.RepaymentPeriodFrequencyTypeEnum;
}
export namespace LoanProductMinimumRepaymentScheduleRelatedDetail {
    export const AmortizationMethodEnum = {
        EqualPrincipal: 'EQUAL_PRINCIPAL',
        EqualInstallments: 'EQUAL_INSTALLMENTS',
        Invalid: 'INVALID'
    } as const;
    export type AmortizationMethodEnum = typeof AmortizationMethodEnum[keyof typeof AmortizationMethodEnum];
    export const DaysInYearCustomStrategyEnum = {
        FullLeapYear: 'FULL_LEAP_YEAR',
        Feb29PeriodOnly: 'FEB_29_PERIOD_ONLY'
    } as const;
    export type DaysInYearCustomStrategyEnum = typeof DaysInYearCustomStrategyEnum[keyof typeof DaysInYearCustomStrategyEnum];
    export const InterestCalculationPeriodMethodEnum = {
        Daily: 'DAILY',
        SameAsRepaymentPeriod: 'SAME_AS_REPAYMENT_PERIOD',
        Invalid: 'INVALID'
    } as const;
    export type InterestCalculationPeriodMethodEnum = typeof InterestCalculationPeriodMethodEnum[keyof typeof InterestCalculationPeriodMethodEnum];
    export const InterestMethodEnum = {
        DecliningBalance: 'DECLINING_BALANCE',
        Flat: 'FLAT',
        Invalid: 'INVALID'
    } as const;
    export type InterestMethodEnum = typeof InterestMethodEnum[keyof typeof InterestMethodEnum];
    export const InterestPeriodFrequencyTypeEnum = {
        Days: 'DAYS',
        Weeks: 'WEEKS',
        Months: 'MONTHS',
        Years: 'YEARS',
        WholeTerm: 'WHOLE_TERM',
        Invalid: 'INVALID'
    } as const;
    export type InterestPeriodFrequencyTypeEnum = typeof InterestPeriodFrequencyTypeEnum[keyof typeof InterestPeriodFrequencyTypeEnum];
    export const RepaymentPeriodFrequencyTypeEnum = {
        Days: 'DAYS',
        Weeks: 'WEEKS',
        Months: 'MONTHS',
        Years: 'YEARS',
        WholeTerm: 'WHOLE_TERM',
        Invalid: 'INVALID'
    } as const;
    export type RepaymentPeriodFrequencyTypeEnum = typeof RepaymentPeriodFrequencyTypeEnum[keyof typeof RepaymentPeriodFrequencyTypeEnum];
}


