/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface LoanProductBorrowerCycleVariationData { 
    borrowerCycleNumber?: number;
    defaultValue?: number;
    id?: number;
    loanProductParamType?: LoanProductBorrowerCycleVariationData.LoanProductParamTypeEnum;
    loanProductValueConditionType?: LoanProductBorrowerCycleVariationData.LoanProductValueConditionTypeEnum;
    maxValue?: number;
    minValue?: number;
    paramType?: EnumOptionData;
    valueConditionType?: EnumOptionData;
}
export namespace LoanProductBorrowerCycleVariationData {
    export const LoanProductParamTypeEnum = {
        Invalid: 'INVALID',
        Principal: 'PRINCIPAL',
        Interestrate: 'INTERESTRATE',
        Repayment: 'REPAYMENT'
    } as const;
    export type LoanProductParamTypeEnum = typeof LoanProductParamTypeEnum[keyof typeof LoanProductParamTypeEnum];
    export const LoanProductValueConditionTypeEnum = {
        Invalid: 'INVALID',
        Equal: 'EQUAL',
        Greaterthan: 'GREATERTHAN'
    } as const;
    export type LoanProductValueConditionTypeEnum = typeof LoanProductValueConditionTypeEnum[keyof typeof LoanProductValueConditionTypeEnum];
}


