/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanProduct } from './loanProduct';


export interface LoanProductPaymentAllocationRule { 
    allocationTypes?: Array<LoanProductPaymentAllocationRule.AllocationTypesEnum>;
    createdBy: number;
    createdDate: string;
    futureInstallmentAllocationRule?: LoanProductPaymentAllocationRule.FutureInstallmentAllocationRuleEnum;
    id?: number;
    lastModifiedBy: number;
    lastModifiedDate: string;
    loanProduct?: LoanProduct;
    'new'?: boolean;
    transactionType?: LoanProductPaymentAllocationRule.TransactionTypeEnum;
}
export namespace LoanProductPaymentAllocationRule {
    export const AllocationTypesEnum = {
        PastDuePenalty: 'PAST_DUE_PENALTY',
        PastDueFee: 'PAST_DUE_FEE',
        PastDuePrincipal: 'PAST_DUE_PRINCIPAL',
        PastDueInterest: 'PAST_DUE_INTEREST',
        DuePenalty: 'DUE_PENALTY',
        DueFee: 'DUE_FEE',
        DuePrincipal: 'DUE_PRINCIPAL',
        DueInterest: 'DUE_INTEREST',
        InAdvancePenalty: 'IN_ADVANCE_PENALTY',
        InAdvanceFee: 'IN_ADVANCE_FEE',
        InAdvancePrincipal: 'IN_ADVANCE_PRINCIPAL',
        InAdvanceInterest: 'IN_ADVANCE_INTEREST'
    } as const;
    export type AllocationTypesEnum = typeof AllocationTypesEnum[keyof typeof AllocationTypesEnum];
    export const FutureInstallmentAllocationRuleEnum = {
        NextInstallment: 'NEXT_INSTALLMENT',
        LastInstallment: 'LAST_INSTALLMENT',
        NextLastInstallment: 'NEXT_LAST_INSTALLMENT',
        Reamortization: 'REAMORTIZATION'
    } as const;
    export type FutureInstallmentAllocationRuleEnum = typeof FutureInstallmentAllocationRuleEnum[keyof typeof FutureInstallmentAllocationRuleEnum];
    export const TransactionTypeEnum = {
        Default: 'DEFAULT',
        Repayment: 'REPAYMENT',
        DownPayment: 'DOWN_PAYMENT',
        MerchantIssuedRefund: 'MERCHANT_ISSUED_REFUND',
        PayoutRefund: 'PAYOUT_REFUND',
        GoodwillCredit: 'GOODWILL_CREDIT',
        ChargeRefund: 'CHARGE_REFUND',
        ChargeAdjustment: 'CHARGE_ADJUSTMENT',
        WaiveInterest: 'WAIVE_INTEREST',
        ChargePayment: 'CHARGE_PAYMENT',
        RefundForActiveLoan: 'REFUND_FOR_ACTIVE_LOAN',
        InterestPaymentWaiver: 'INTEREST_PAYMENT_WAIVER',
        InterestRefund: 'INTEREST_REFUND',
        CapitalizedIncomeAdjustment: 'CAPITALIZED_INCOME_ADJUSTMENT'
    } as const;
    export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];
}


