/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanProduct } from './loanProduct';


export interface LoanProductCreditAllocationRule { 
    allocationTypes?: Array<LoanProductCreditAllocationRule.AllocationTypesEnum>;
    createdBy: number;
    createdDate: string;
    id?: number;
    lastModifiedBy: number;
    lastModifiedDate: string;
    loanProduct?: LoanProduct;
    'new'?: boolean;
    transactionType?: LoanProductCreditAllocationRule.TransactionTypeEnum;
}
export namespace LoanProductCreditAllocationRule {
    export const AllocationTypesEnum = {
        Penalty: 'PENALTY',
        Fee: 'FEE',
        Principal: 'PRINCIPAL',
        Interest: 'INTEREST'
    } as const;
    export type AllocationTypesEnum = typeof AllocationTypesEnum[keyof typeof AllocationTypesEnum];
    export const TransactionTypeEnum = {
        Chargeback: 'CHARGEBACK'
    } as const;
    export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];
}


