/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanTermTypeOptions } from './loanTermTypeOptions';


export interface LoanTermVariationsData { 
    dateValue?: string;
    decimalValue?: number;
    id?: number;
    isProcessed?: boolean;
    isSpecificToInstallment?: boolean;
    termType?: LoanTermTypeOptions;
    termVariationApplicableFrom?: string;
}

