/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanProductBorrowerCycleVariations { 
    borrowerCycleNumber?: number;
    defaultValue?: number;
    id?: number;
    maxValue?: number;
    minValue?: number;
    'new'?: boolean;
    paramType?: LoanProductBorrowerCycleVariations.ParamTypeEnum;
    valueConditionType?: LoanProductBorrowerCycleVariations.ValueConditionTypeEnum;
}
export namespace LoanProductBorrowerCycleVariations {
    export const ParamTypeEnum = {
        Invalid: 'INVALID',
        Principal: 'PRINCIPAL',
        Interestrate: 'INTERESTRATE',
        Repayment: 'REPAYMENT'
    } as const;
    export type ParamTypeEnum = typeof ParamTypeEnum[keyof typeof ParamTypeEnum];
    export const ValueConditionTypeEnum = {
        Invalid: 'INVALID',
        Equal: 'EQUAL',
        Greaterthan: 'GREATERTHAN'
    } as const;
    export type ValueConditionTypeEnum = typeof ValueConditionTypeEnum[keyof typeof ValueConditionTypeEnum];
}


