/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanAccountLock { 
    error?: string;
    loanId?: number;
    lockOwner?: LoanAccountLock.LockOwnerEnum;
    lockPlacedOn?: string;
    lockPlacedOnCobBusinessDate?: string;
    newLockOwner?: LoanAccountLock.NewLockOwnerEnum;
    stacktrace?: string;
    version?: number;
}
export namespace LoanAccountLock {
    export const LockOwnerEnum = {
        LoanCobChunkProcessing: 'LOAN_COB_CHUNK_PROCESSING',
        LoanInlineCobProcessing: 'LOAN_INLINE_COB_PROCESSING'
    } as const;
    export type LockOwnerEnum = typeof LockOwnerEnum[keyof typeof LockOwnerEnum];
    export const NewLockOwnerEnum = {
        LoanCobChunkProcessing: 'LOAN_COB_CHUNK_PROCESSING',
        LoanInlineCobProcessing: 'LOAN_INLINE_COB_PROCESSING'
    } as const;
    export type NewLockOwnerEnum = typeof NewLockOwnerEnum[keyof typeof NewLockOwnerEnum];
}


