/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanProduct } from './loanProduct';


export interface LoanProductGuaranteeDetails { 
    id?: number;
    loanProduct?: LoanProduct;
    mandatoryGuarantee?: number;
    minimumGuaranteeFromGuarantor?: number;
    minimumGuaranteeFromOwnFunds?: number;
    'new'?: boolean;
}

