/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanProductProvisioningEntryData { 
    amountreserved?: number;
    balance?: number;
    categoryId?: number;
    categoryName?: string;
    criteriaId?: number;
    currencyCode?: string;
    expenseAccount?: number;
    expenseAccountCode?: string;
    expenseAccountName?: string;
    historyId?: number;
    liabilityAccountCode?: string;
    liabilityAccountName?: string;
    liablityAccount?: number;
    officeId?: number;
    officeName?: string;
    overdueInDays?: number;
    percentage?: number;
    productId?: number;
    productName?: string;
}

