/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentTypeData } from './paymentTypeData';
import { AccountTransferData } from './accountTransferData';
import { CurrencyData } from './currencyData';
import { LoanTransactionRelationData } from './loanTransactionRelationData';
import { ExternalId } from './externalId';
import { LoanRepaymentScheduleInstallmentData } from './loanRepaymentScheduleInstallmentData';
import { CodeValueData } from './codeValueData';
import { LoanChargePaidByData } from './loanChargePaidByData';
import { PaymentDetailData } from './paymentDetailData';
import { LoanTransactionEnumData } from './loanTransactionEnumData';


export interface LoanTransactionData { 
    accountId?: number;
    accountNumber?: string;
    amount?: number;
    bankNumber?: number;
    chargeOffReasonOptions?: Array<CodeValueData>;
    checkNumber?: number;
    currency?: CurrencyData;
    date?: string;
    dateFormat?: string;
    externalId?: ExternalId;
    externalLoanId?: ExternalId;
    feeChargesPortion?: number;
    fixedEmiAmount?: number;
    id?: number;
    interestPortion?: number;
    loanChargePaidByList?: Array<LoanChargePaidByData>;
    loanId?: number;
    loanRepaymentScheduleInstallments?: Array<LoanRepaymentScheduleInstallmentData>;
    loanTransactionRelations?: Array<LoanTransactionRelationData>;
    locale?: string;
    manuallyReversed?: boolean;
    netDisbursalAmount?: number;
    notDisbursement?: boolean;
    numberOfRepayments?: number;
    officeId?: number;
    officeName?: string;
    outstandingLoanBalance?: number;
    overpaymentPortion?: number;
    paymentDetailData?: PaymentDetailData;
    paymentTypeId?: number;
    paymentTypeOptions?: Array<PaymentTypeData>;
    penaltyChargesPortion?: number;
    possibleNextRepaymentDate?: string;
    principalPortion?: number;
    receiptNumber?: number;
    reversalExternalId?: ExternalId;
    reversedOnDate?: string;
    routingCode?: number;
    rowIndex?: number;
    submittedOnDate?: string;
    transactionAmount?: number;
    transactionDate?: string;
    transactionRelations?: Array<LoanTransactionRelationData>;
    transactionType?: string;
    transfer?: AccountTransferData;
    type?: LoanTransactionEnumData;
    unrecognizedIncomePortion?: number;
    writeOffReasonOptions?: Array<CodeValueData>;
}

