/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanAccountLock } from './loanAccountLock';


export interface LoanAccountLockResponseDTO { 
    content?: Array<LoanAccountLock>;
    limit?: number;
    page?: number;
}

