/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanTransactionEnumData { 
    accrual?: boolean;
    accrualActivity?: boolean;
    accrualAdjustment?: boolean;
    approveTransfer?: boolean;
    capitalizedIncome?: boolean;
    capitalizedIncomeAdjustment?: boolean;
    capitalizedIncomeAmortization?: boolean;
    capitalizedIncomeAmortizationAdjustment?: boolean;
    chargeAdjustment?: boolean;
    chargePayment?: boolean;
    chargeRefund?: boolean;
    chargeback?: boolean;
    chargeoff?: boolean;
    code?: string;
    contra?: boolean;
    creditBalanceRefund?: boolean;
    disbursement?: boolean;
    downPayment?: boolean;
    goodwillCredit?: boolean;
    id?: number;
    initiateTransfer?: boolean;
    interestPaymentWaiver?: boolean;
    interestRefund?: boolean;
    merchantIssuedRefund?: boolean;
    payoutRefund?: boolean;
    reAge?: boolean;
    reAmortize?: boolean;
    recoveryRepayment?: boolean;
    refund?: boolean;
    refundForActiveLoans?: boolean;
    rejectTransfer?: boolean;
    repayment?: boolean;
    repaymentAtDisbursement?: boolean;
    repaymentType?: boolean;
    value?: string;
    waiveCharges?: boolean;
    waiveInterest?: boolean;
    withdrawTransfer?: boolean;
    writeOff?: boolean;
}

