/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanTransactionRelationData { 
    amount?: number;
    fromLoanTransaction?: number;
    paymentType?: string;
    relationType?: LoanTransactionRelationData.RelationTypeEnum;
    toLoanCharge?: number;
    toLoanTransaction?: number;
}
export namespace LoanTransactionRelationData {
    export const RelationTypeEnum = {
        Invalid: 'INVALID',
        Chargeback: 'CHARGEBACK',
        ChargeAdjustment: 'CHARGE_ADJUSTMENT',
        Replayed: 'REPLAYED',
        Related: 'RELATED',
        Adjustment: 'ADJUSTMENT'
    } as const;
    export type RelationTypeEnum = typeof RelationTypeEnum[keyof typeof RelationTypeEnum];
}


