/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MediaType { 
    parameters?: { [key: string]: string; };
    subtype?: string;
    type?: string;
    wildcardSubtype?: boolean;
    wildcardType?: boolean;
}

