/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface NoteData { 
    clientId?: number;
    createdById?: number;
    createdByUsername?: string;
    createdOn?: string;
    depositAccountId?: number;
    groupId?: number;
    id?: number;
    loanId?: number;
    loanTransactionId?: number;
    note?: string;
    noteType?: EnumOptionData;
    savingAccountId?: number;
    updatedById?: number;
    updatedByUsername?: string;
    updatedOn?: string;
}

