/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientTextSearch } from './clientTextSearch';
import { SortOrder } from './sortOrder';


export interface PagedRequestClientTextSearch { 
    page?: number;
    request?: ClientTextSearch;
    size?: number;
    sorts?: Array<SortOrder>;
}

