/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdvancedQueryRequest } from './advancedQueryRequest';
import { SortOrder } from './sortOrder';
import { PagedLocalRequestAdvancedQueryDataLocaleObject } from './pagedLocalRequestAdvancedQueryDataLocaleObject';


export interface PagedLocalRequestAdvancedQueryRequest { 
    dateFormat?: string;
    dateTimeFormat?: string;
    locale?: string;
    localeObject?: PagedLocalRequestAdvancedQueryDataLocaleObject;
    page?: number;
    request?: AdvancedQueryRequest;
    size?: number;
    sorts?: Array<SortOrder>;
}

