/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostClientsClientIdChargesChargeIdRequest
 */
export interface PostClientsClientIdChargesChargeIdRequest { 
    amount?: number;
    dateFormat?: string;
    externalId?: string;
    locale?: string;
    transactionDate?: string;
}

