/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest
 */
export interface PostRecurringDepositAccountsRecurringDepositAccountIdTransactionsRequest { 
    accountNumber?: string;
    bankNumber?: string;
    checkNumber?: string;
    dateFormat?: string;
    locale?: string;
    paymentTypeId?: number;
    receiptNumber?: string;
    routingCode?: string;
    transactionAmount?: number;
    transactionDate?: string;
}

