/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetSelfUserDetailsRoles } from './getSelfUserDetailsRoles';
import { GetSelfUserDetailsOrganisationalRole } from './getSelfUserDetailsOrganisationalRole';


/**
 * PostSelfAuthenticationResponse
 */
export interface PostSelfAuthenticationResponse { 
    authenticated?: boolean;
    base64EncodedAuthenticationKey?: string;
    clients?: Array<number>;
    isSelfServiceUser?: boolean;
    officeId?: number;
    officeName?: string;
    organisationalRole?: GetSelfUserDetailsOrganisationalRole;
    permissions?: Array<string>;
    roles?: Set<GetSelfUserDetailsRoles>;
    staffDisplayName?: string;
    staffId?: number;
    userId?: number;
    username?: string;
}

