/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostSavingsAccountsRequest
 */
export interface PostSavingsAccountsRequest { 
    clientId?: number;
    dateFormat?: string;
    externalId?: string;
    locale?: string;
    productId?: number;
    submittedOnDate?: string;
}

