/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostRepostRequest
 */
export interface PostRepostRequest { 
    description?: string;
    reportCategory?: string;
    reportName?: string;
    reportParameters?: Array<object>;
    reportSql?: string;
    reportSubType?: string;
    reportType?: string;
}

