/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemplateMapper } from './templateMapper';


/**
 * PostTemplatesRequest
 */
export interface PostTemplatesRequest { 
    entity?: number;
    id?: number;
    mappers?: Array<TemplateMapper>;
    name?: string;
    text?: string;
    type?: number;
}

