/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalAssetOwnerTransferChangesData } from './externalAssetOwnerTransferChangesData';


/**
 * PostInitiateTransferResponse
 */
export interface PostInitiateTransferResponse { 
    changes?: ExternalAssetOwnerTransferChangesData;
    dateFormat?: string;
    locale?: string;
    /**
     * transfer external ID
     */
    resourceExternalId?: string;
    /**
     * transfer ID
     */
    resourceId?: number;
    /**
     * loan external ID
     */
    subResourceExternalId?: string;
    /**
     * loan ID
     */
    subResourceId?: number;
}

