/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostLoansLoanIdTransactionsResponseChanges } from './postLoansLoanIdTransactionsResponseChanges';


/**
 * PostLoansLoanIdTransactionsResponse
 */
export interface PostLoansLoanIdTransactionsResponse { 
    changes?: PostLoansLoanIdTransactionsResponseChanges;
    clientId?: number;
    loanId?: number;
    officeId?: number;
    resourceExternalId?: string;
    resourceId?: number;
    subResourceExternalId?: string;
    subResourceId?: number;
}

