/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostRecurringChanges { 
    accountNumber?: string;
    bankNumber?: string;
    checkNumber?: string;
    receiptNumber?: string;
    routingCode?: string;
}

