/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostSavingsCharges } from './postSavingsCharges';


/**
 * PostSavingsProductsRequest
 */
export interface PostSavingsProductsRequest { 
    accountMappingForPayment?: string;
    accountingRule?: number;
    charges?: Set<PostSavingsCharges>;
    currencyCode?: string;
    description?: string;
    digitsAfterDecimal?: number;
    inMultiplesOf?: number;
    interestCalculationDaysInYearType?: number;
    interestCalculationType?: number;
    interestCompoundingPeriodType?: number;
    interestPostingPeriodType?: number;
    locale?: string;
    name?: string;
    nominalAnnualInterestRate?: number;
    shortName?: string;
}

