/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostRecurringDepositAccountsResponse
 */
export interface PostRecurringDepositAccountsResponse { 
    clientId?: number;
    officeId?: number;
    resourceId?: number;
    savingsId?: number;
}

