/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostTellersTellerIdCashiersCashierIdSettleRequest
 */
export interface PostTellersTellerIdCashiersCashierIdSettleRequest { 
    currencyCode?: string;
    dateFormat?: string;
    locale?: string;
    txnAmount?: number;
    txnDate?: string;
    txnNote?: string;
}

