/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostLoansRepaymentSchedulePeriods { 
    dueDate?: string;
    feeChargesDue?: number;
    feeChargesOutstanding?: number;
    period?: number;
    principalDisbursed?: number;
    principalLoanBalanceOutstanding?: number;
    totalActualCostOfLoanForPeriod?: number;
    totalDueForPeriod?: number;
    totalOriginalDueForPeriod?: number;
    totalOutstandingForPeriod?: number;
    totalOverdue?: number;
}

