/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostTellersRequest
 */
export interface PostTellersRequest { 
    dateFormat?: string;
    description?: string;
    locale?: string;
    name?: string;
    officeId?: number;
    startDate?: string;
    status?: PostTellersRequest.StatusEnum;
}
export namespace PostTellersRequest {
    export const StatusEnum = {
        Invalid: 'INVALID',
        Pending: 'PENDING',
        Active: 'ACTIVE',
        Inactive: 'INACTIVE',
        Closed: 'CLOSED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


