/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostLoansLoanIdTransactionsRequest
 */
export interface PostLoansLoanIdTransactionsRequest { 
    accountNumber?: string;
    bankNumber?: string;
    chargeOffReasonId?: number;
    checkNumber?: string;
    dateFormat?: string;
    dueDate?: string;
    externalId?: string;
    frequencyNumber?: number;
    frequencyType?: string;
    loanChargeId?: number;
    locale?: string;
    note?: string;
    numberOfInstallments?: number;
    paymentTypeId?: number;
    receiptNumber?: string;
    reversalExternalId?: string;
    routingCode?: string;
    startDate?: string;
    transactionAmount?: number;
    transactionDate?: string;
    writeoffReasonId?: number;
}

