/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostTellersTellerIdCashiersRequest
 */
export interface PostTellersTellerIdCashiersRequest { 
    dateFormat?: string;
    description?: string;
    endDate?: string;
    isFullDay?: boolean;
    locale?: string;
    staffId?: number;
    startDate?: string;
}

