/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostGLAccountsRequest
 */
export interface PostGLAccountsRequest { 
    description?: string;
    glCode?: string;
    manualEntriesAllowed?: boolean;
    name?: string;
    parentId?: number;
    tagId?: number;
    type?: number;
    usage?: number;
}

