/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostLoansLoanIdChargesChargeIdRequest
 */
export interface PostLoansLoanIdChargesChargeIdRequest { 
    accountNumber?: string;
    amount?: number;
    bankNumber?: string;
    chargeId?: number;
    checkNumber?: string;
    dateFormat?: string;
    dueDate?: string;
    externalId?: string;
    installmentNumber?: number;
    locale?: string;
    note?: string;
    paymentTypeId?: number;
    receiptNumber?: string;
    routingCode?: string;
    transactionDate?: string;
}

