/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostClientsDatatable } from './postClientsDatatable';
import { ClientAddressRequest } from './clientAddressRequest';


/**
 * PostClientsRequest
 */
export interface PostClientsRequest { 
    activationDate?: string;
    active?: boolean;
    /**
     * Address requests
     */
    address?: Array<ClientAddressRequest>;
    /**
     * List of PostClientsDatatable
     */
    datatables?: Array<PostClientsDatatable>;
    dateFormat?: string;
    dateOfBirth?: string;
    emailAddress?: string;
    externalId?: string;
    firstname?: string;
    fullname?: string;
    groupId?: number;
    lastname?: string;
    legalFormId?: number;
    locale?: string;
    middlename?: string;
    mobileNo?: string;
    officeId?: number;
}

