/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostLoansDelinquencyActionRequest
 */
export interface PostLoansDelinquencyActionRequest { 
    action?: string;
    dateFormat?: string;
    endDate?: string;
    locale?: string;
    startDate?: string;
}

