/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostRecurringDepositAccountsRequest
 */
export interface PostRecurringDepositAccountsRequest { 
    clientId?: number;
    dateFormat?: string;
    depositAmount?: number;
    depositPeriod?: number;
    depositPeriodFrequencyId?: number;
    isCalendarInherited?: boolean;
    locale?: string;
    mandatoryRecommendedDepositAmount?: number;
    productId?: number;
    recurringFrequency?: number;
    recurringFrequencyType?: number;
    submittedOnDate?: string;
}

