/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Field } from './field';
import { Event } from './event';


/**
 * PostHookRequest
 */
export interface PostHookRequest { 
    config?: Array<Field>;
    displayName?: string;
    events?: Array<Event>;
    isActive?: boolean;
    name?: string;
    templateId?: number;
}

