/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostLoansLoanIdDisbursementData } from './postLoansLoanIdDisbursementData';


/**
 * PostLoansLoanIdRequest
 */
export interface PostLoansLoanIdRequest { 
    actualDisbursementDate?: string;
    adjustRepaymentDate?: string;
    approvedLoanAmount?: number;
    approvedOnDate?: string;
    assignmentDate?: string;
    dateFormat?: string;
    /**
     * List of PostLoansLoanIdDisbursementData
     */
    disbursementData?: Array<PostLoansLoanIdDisbursementData>;
    expectedDisbursementDate?: string;
    externalId?: string;
    fixedEmiAmount?: number;
    fromLoanOfficerId?: number;
    locale?: string;
    note?: string;
    paymentTypeId?: number;
    rejectedOnDate?: string;
    toLoanOfficerId?: number;
    transactionAmount?: number;
    unassignedDate?: string;
    withdrawnOnDate?: string;
}

