/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PostInterestRateChartsRequest
 */
export interface PostInterestRateChartsRequest { 
    dateFormat?: string;
    description?: string;
    fromDate?: string;
    locale?: string;
    name?: string;
    type?: string;
}

