/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProvisioningCriteriaDefinitionData { 
    categoryId?: number;
    categoryName?: string;
    expenseAccount?: number;
    expenseCode?: string;
    expenseName?: string;
    id?: number;
    liabilityAccount?: number;
    liabilityCode?: string;
    liabilityName?: string;
    maxAge?: number;
    minAge?: number;
    provisioningPercentage?: number;
}

