/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanProductProvisioningEntryData } from './loanProductProvisioningEntryData';


export interface ProvisioningEntryData { 
    createdById?: number;
    createdDate?: string;
    createdUser?: string;
    id?: number;
    journalEntry?: boolean;
    modifiedById?: number;
    modifiedUser?: string;
    provisioningEntries?: Array<LoanProductProvisioningEntryData>;
    reservedAmount?: number;
}

