/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PutChargesChargeIdRequest
 */
export interface PutChargesChargeIdRequest { 
    active?: boolean;
    amount?: number;
    chargeAppliesTo?: number;
    chargeCalculationType?: number;
    chargePaymentMode?: number;
    chargeTimeType?: number;
    countFrequencyType?: number;
    currencyCode?: string;
    enableFreeWithdrawalCharge?: boolean;
    enablePaymentType?: boolean;
    feeFrequency?: string;
    feeInterval?: number;
    feeOnMonthDay?: string;
    freeWithdrawalFrequency?: number;
    locale?: string;
    maxCap?: number;
    minCap?: number;
    monthDayFormat?: string;
    name?: string;
    paymentTypeId?: number;
    penalty?: boolean;
    restartCountFrequency?: number;
}

