/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PutChargeTransactionChangesResponseChanges { 
    amount?: number;
    date?: string;
    externalId?: string;
    feeChargesPortion?: number;
    id?: number;
    interestPortion?: number;
    outstandingLoanBalance?: number;
    penaltyChargesPortion?: number;
    principalPortion?: number;
}

