/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PutChargeTransactionChangesResponseChanges } from './putChargeTransactionChangesResponseChanges';


/**
 * PutChargeTransactionChangesResponse
 */
export interface PutChargeTransactionChangesResponse { 
    changes?: PutChargeTransactionChangesResponseChanges;
    clientId?: number;
    loanId?: number;
    officeId?: number;
    resourceExternalId?: string;
    resourceId?: number;
    subResourceExternalId?: string;
    subResourceId?: number;
}

