/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PutDataTablesRequestAddColumns } from './putDataTablesRequestAddColumns';
import { PutDataTablesRequestDropColumns } from './putDataTablesRequestDropColumns';
import { PutDataTablesRequestChangeColumns } from './putDataTablesRequestChangeColumns';


/**
 * PutDataTablesRequest
 */
export interface PutDataTablesRequest { 
    addColumns?: Array<PutDataTablesRequestAddColumns>;
    apptableName?: string;
    changeColumns?: Array<PutDataTablesRequestChangeColumns>;
    dropColumns?: Array<PutDataTablesRequestDropColumns>;
}

