/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PutDataTablesAppTableIdResponse
 */
export interface PutDataTablesAppTableIdResponse { 
    changes?: { [key: string]: object; };
    clientId?: number;
    loanId?: number;
    officeId?: number;
    resourceId?: number;
}

