/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PutGroupsGroupIdChanges } from './putGroupsGroupIdChanges';


/**
 * PutGroupsGroupIdResponse
 */
export interface PutGroupsGroupIdResponse { 
    changes?: PutGroupsGroupIdChanges;
    groupId?: number;
    officeId?: number;
    resourceId?: number;
}

