/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoansLoanIdCollateralsRequest } from './loansLoanIdCollateralsRequest';


/**
 * PutLoansLoanIdCollateralsCollateralIdResponse
 */
export interface PutLoansLoanIdCollateralsCollateralIdResponse { 
    changes?: LoansLoanIdCollateralsRequest;
    loanId?: number;
    resourceId?: number;
}

