/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PutLoansLoanIdDisbursementData { 
    dateFormat?: string;
    expectedDisbursementDate?: string;
    interestType?: number;
    isEqualAmortization?: boolean;
    locale?: string;
    netDisbursalAmount?: number;
    principal?: number;
}

