/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PutOfficesOfficeIdResponseChanges } from './putOfficesOfficeIdResponseChanges';


/**
 * PutOfficesOfficeIdResponse
 */
export interface PutOfficesOfficeIdResponse { 
    changes?: PutOfficesOfficeIdResponseChanges;
    officeId?: number;
    resourceId?: number;
}

