/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PutOfficesOfficeIdRequest
 */
export interface PutOfficesOfficeIdRequest { 
    dateFormat?: string;
    externalId?: string;
    locale?: string;
    name?: string;
    openingDate?: string;
}

