/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PutPaymentTypesPaymentTypeIdRequest
 */
export interface PutPaymentTypesPaymentTypeIdRequest { 
    codeName?: string;
    description?: string;
    isCashPayment?: boolean;
    isSystemDefined?: boolean;
    name?: string;
    position?: number;
}

