/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PutSavingsAccountsChanges } from './putSavingsAccountsChanges';


/**
 * PutSavingsAccountsAccountIdResponse
 */
export interface PutSavingsAccountsAccountIdResponse { 
    changes?: PutSavingsAccountsChanges;
    clientId?: number;
    officeId?: number;
    resourceId?: number;
    savingsId?: number;
}

