/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PutSavingsProductsProductIdRequest
 */
export interface PutSavingsProductsProductIdRequest { 
    description?: string;
    interestRate?: number;
    locale?: string;
}

