/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PutSelfLoansLoanIdRequest
 */
export interface PutSelfLoansLoanIdRequest { 
    amortizationType?: number;
    dateFormat?: string;
    expectedDisbursementDate?: string;
    interestCalculationPeriodType?: number;
    interestRatePerPeriod?: number;
    interestType?: number;
    loanTermFrequency?: number;
    loanTermFrequencyType?: number;
    locale?: string;
    numberOfRepayments?: number;
    principal?: number;
    productId?: number;
    repaymentEvery?: number;
    repaymentFrequencyType?: number;
    transactionProcessingStrategyCode?: string;
}

