/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PutTellersResponseChanges } from './putTellersResponseChanges';


/**
 * PutTellersResponse
 */
export interface PutTellersResponse { 
    changes?: PutTellersResponseChanges;
    officeId?: number;
    resourceId?: number;
}

