/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PutUsersUserIdRequest
 */
export interface PutUsersUserIdRequest { 
    clients?: Array<number>;
    email?: string;
    firstname?: string;
    isSelfServiceUser?: boolean;
    lastname?: string;
    officeId?: number;
    password?: string;
    repeatPassword?: string;
    roles?: Array<number>;
    sendPasswordToEmail?: boolean;
    staffId?: number;
}

