/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface RateData { 
    active?: boolean;
    id?: number;
    name?: string;
    percentage?: number;
    productApply?: EnumOptionData;
}

