/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppUser } from './appUser';


export interface Rate { 
    active?: boolean;
    approveUser?: AppUser;
    createdBy?: number;
    createdDate?: string;
    id?: number;
    lastModifiedBy?: number;
    lastModifiedDate?: string;
    name?: string;
    'new'?: boolean;
    percentage?: number;
    productApply?: number;
}

