/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReportMailingJobTimelineData { 
    createdByFirstname?: string;
    createdByLastname?: string;
    createdByUsername?: string;
    createdOnDate?: string;
    updatedByFirstname?: string;
    updatedByLastname?: string;
    updatedByUsername?: string;
    updatedOnDate?: string;
}

