/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SavingsAccountApplicationTimelineData { 
    activatedByFirstname?: string;
    activatedByLastname?: string;
    activatedByUsername?: string;
    activatedOnDate?: string;
    approvedByFirstname?: string;
    approvedByLastname?: string;
    approvedByUsername?: string;
    approvedOnDate?: string;
    closedByFirstname?: string;
    closedByLastname?: string;
    closedByUsername?: string;
    closedOnDate?: string;
    rejectedByFirstname?: string;
    rejectedByLastname?: string;
    rejectedByUsername?: string;
    rejectedOnDate?: string;
    submittedByFirstname?: string;
    submittedByLastname?: string;
    submittedByUsername?: string;
    submittedOnDate?: string;
    withdrawnByFirstname?: string;
    withdrawnByLastname?: string;
    withdrawnByUsername?: string;
    withdrawnOnDate?: string;
}

