/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SavingsAccountSubStatusEnumData { 
    block?: boolean;
    blockCredit?: boolean;
    blockDebit?: boolean;
    code?: string;
    dormant?: boolean;
    escheat?: boolean;
    id?: number;
    inactive?: boolean;
    none?: boolean;
    value?: string;
}

