/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SavingsAccountTransactionEnumData { 
    accrual?: boolean;
    amountHold?: boolean;
    amountRelease?: boolean;
    annualFee?: boolean;
    approveTransfer?: boolean;
    chargeTransaction?: boolean;
    code?: string;
    credit?: boolean;
    debit?: boolean;
    deposit?: boolean;
    depositOrWithdrawal?: boolean;
    dividendPayout?: boolean;
    entryType?: SavingsAccountTransactionEnumData.EntryTypeEnum;
    escheat?: boolean;
    feeDeduction?: boolean;
    id?: number;
    incomeFromInterest?: boolean;
    initiateTransfer?: boolean;
    interestPosting?: boolean;
    overDraftInterestPosting?: boolean;
    overdraftFee?: boolean;
    overdraftInterest?: boolean;
    payCharge?: boolean;
    rejectTransfer?: boolean;
    transactionTypeEnum?: SavingsAccountTransactionEnumData.TransactionTypeEnumEnum;
    value?: string;
    withdrawTransfer?: boolean;
    withdrawal?: boolean;
    withdrawalFee?: boolean;
    withholdTax?: boolean;
    writtenoff?: boolean;
}
export namespace SavingsAccountTransactionEnumData {
    export const EntryTypeEnum = {
        Credit: 'CREDIT',
        Debit: 'DEBIT'
    } as const;
    export type EntryTypeEnum = typeof EntryTypeEnum[keyof typeof EntryTypeEnum];
    export const TransactionTypeEnumEnum = {
        Invalid: 'INVALID',
        Deposit: 'DEPOSIT',
        Withdrawal: 'WITHDRAWAL',
        InterestPosting: 'INTEREST_POSTING',
        WithdrawalFee: 'WITHDRAWAL_FEE',
        AnnualFee: 'ANNUAL_FEE',
        WaiveCharges: 'WAIVE_CHARGES',
        PayCharge: 'PAY_CHARGE',
        DividendPayout: 'DIVIDEND_PAYOUT',
        Accrual: 'ACCRUAL',
        InitiateTransfer: 'INITIATE_TRANSFER',
        ApproveTransfer: 'APPROVE_TRANSFER',
        WithdrawTransfer: 'WITHDRAW_TRANSFER',
        RejectTransfer: 'REJECT_TRANSFER',
        WrittenOff: 'WRITTEN_OFF',
        OverdraftInterest: 'OVERDRAFT_INTEREST',
        WithholdTax: 'WITHHOLD_TAX',
        Escheat: 'ESCHEAT',
        AmountHold: 'AMOUNT_HOLD',
        AmountRelease: 'AMOUNT_RELEASE'
    } as const;
    export type TransactionTypeEnumEnum = typeof TransactionTypeEnumEnum[keyof typeof TransactionTypeEnumEnum];
}


