/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencyData } from './currencyData';
import { EnumOptionData } from './enumOptionData';


export interface SavingsProductData { 
    accrualBasedAccountingEnabled?: boolean;
    allowOverdraft?: boolean;
    cashBasedAccountingEnabled?: boolean;
    currency?: CurrencyData;
    depositAccountType?: string;
    id?: number;
    interestCalculationDaysInYearType?: EnumOptionData;
    interestCalculationType?: EnumOptionData;
    interestCompoundingPeriodType?: EnumOptionData;
    interestPostingPeriodType?: EnumOptionData;
    lockinPeriodFrequency?: number;
    lockinPeriodFrequencyType?: EnumOptionData;
    maxAllowedLienLimit?: number;
    minRequiredBalance?: number;
    minRequiredOpeningBalance?: number;
    name?: string;
    nominalAnnualInterestRate?: number;
    overdraftLimit?: number;
    periodicAccrualAccounting?: boolean;
    upfrontAccrualAccounting?: boolean;
    withdrawalFeeForTransfers?: boolean;
}

