/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Response } from './response';
import { Survey } from './survey';
import { AppUser } from './appUser';
import { Question } from './question';
import { Client } from './client';


export interface Scorecard { 
    appUser?: AppUser;
    client?: Client;
    createdOn?: string;
    id?: number;
    'new'?: boolean;
    question?: Question;
    response?: Response;
    survey?: Survey;
    value?: number;
}

