/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface SearchData { 
    entityAccountNo?: string;
    entityExternalId?: string;
    entityId?: number;
    entityMobileNo?: string;
    entityName?: string;
    entityStatus?: EnumOptionData;
    entityType?: string;
    parentId?: number;
    parentName?: string;
    parentType?: string;
    subEntityType?: string;
}

