/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface ShareAccountTransactionData { 
    accountId?: number;
    amount?: number;
    amountPaid?: number;
    chargeAmount?: number;
    id?: number;
    numberOfShares?: number;
    purchasedDate?: string;
    purchasedPrice?: number;
    status?: EnumOptionData;
    type?: EnumOptionData;
}

