/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShareAccountDividendData } from './shareAccountDividendData';
import { ShareAccountSummaryData } from './shareAccountSummaryData';
import { ShareAccountTransactionData } from './shareAccountTransactionData';
import { CurrencyData } from './currencyData';
import { ShareAccountStatusEnumData } from './shareAccountStatusEnumData';
import { SavingsAccountData } from './savingsAccountData';
import { ShareAccountChargeData } from './shareAccountChargeData';
import { ChargeData } from './chargeData';
import { EnumOptionData } from './enumOptionData';
import { ShareAccountApplicationTimelineData } from './shareAccountApplicationTimelineData';


export interface ShareAccountData { 
    accountNo?: string;
    allowDividendCalculationForInactiveClients?: boolean;
    applicationDate?: string;
    chargeOptions?: Array<ChargeData>;
    charges?: Array<ShareAccountChargeData>;
    clientId?: number;
    clientName?: string;
    clientSavingsAccounts?: Array<SavingsAccountData>;
    currency?: CurrencyData;
    currentMarketPrice?: number;
    dateFormat?: string;
    defaultShares?: number;
    dividends?: Array<ShareAccountDividendData>;
    externalId?: string;
    id?: number;
    locale?: string;
    lockPeriodTypeEnum?: EnumOptionData;
    lockinPeriod?: number;
    lockinPeriodFrequency?: number;
    lockinPeriodFrequencyType?: number;
    lockinPeriodFrequencyTypeOptions?: Array<EnumOptionData>;
    minimumActivePeriod?: number;
    minimumActivePeriodFrequencyType?: number;
    minimumActivePeriodFrequencyTypeOptions?: Array<EnumOptionData>;
    minimumActivePeriodTypeEnum?: EnumOptionData;
    productId?: number;
    productName?: string;
    productOptions?: Array<object>;
    purchasedShares?: Array<ShareAccountTransactionData>;
    requestedShares?: number;
    rowIndex?: number;
    savingsAccountId?: number;
    savingsAccountNumber?: string;
    status?: ShareAccountStatusEnumData;
    submittedDate?: string;
    summary?: ShareAccountSummaryData;
    timeline?: ShareAccountApplicationTimelineData;
}

