/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShareAccountApplicationTimelineData { 
    activatedByFirstname?: string;
    activatedByLastname?: string;
    activatedByUsername?: string;
    activatedDate?: string;
    approvedByFirstname?: string;
    approvedByLastname?: string;
    approvedByUsername?: string;
    approvedDate?: string;
    closedByFirstname?: string;
    closedByLastname?: string;
    closedByUsername?: string;
    closedDate?: string;
    rejectedByFirstname?: string;
    rejectedByLastname?: string;
    rejectedByUsername?: string;
    rejectedDate?: string;
    submittedByFirstname?: string;
    submittedByLastname?: string;
    submittedByUsername?: string;
    submittedOnDate?: string;
}

