/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencyData } from './currencyData';
import { ShareAccountStatusEnumData } from './shareAccountStatusEnumData';
import { ShareAccountApplicationTimelineData } from './shareAccountApplicationTimelineData';


export interface ShareAccountSummaryData { 
    accountNo?: string;
    currency?: CurrencyData;
    externalId?: string;
    id?: number;
    productId?: number;
    productName?: string;
    shortProductName?: string;
    status?: ShareAccountStatusEnumData;
    timeline?: ShareAccountApplicationTimelineData;
    totalApprovedShares?: number;
    totalPendingForApprovalShares?: number;
}

