/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfficeData } from './officeData';


export interface StaffData { 
    allowedOffices?: Array<OfficeData>;
    dateFormat?: string;
    displayName?: string;
    externalId?: string;
    firstname?: string;
    id?: number;
    isActive?: boolean;
    isLoanOfficer?: boolean;
    joiningDate?: string;
    lastname?: string;
    locale?: string;
    mobileNo?: string;
    officeId?: number;
    officeName?: string;
    rowIndex?: number;
}

