/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StaffRequest { 
    dateFormat?: string;
    externalId?: string;
    firstname?: string;
    forceStatus?: boolean;
    isActive?: boolean;
    isLoanOfficer?: boolean;
    joiningDate?: string;
    lastname?: string;
    locale?: string;
    mobileNo?: string;
    officeId?: number;
}

