/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PortfolioAccountData } from './portfolioAccountData';
import { ClientData } from './clientData';


export interface StandingInstructionData { 
    accountDetailId?: number;
    amount?: number;
    fromAccount?: PortfolioAccountData;
    fromAccountType?: StandingInstructionData.FromAccountTypeEnum;
    fromClient?: ClientData;
    id?: number;
    instructionType?: StandingInstructionData.InstructionTypeEnum;
    name?: string;
    recurrenceFrequency?: StandingInstructionData.RecurrenceFrequencyEnum;
    recurrenceInterval?: number;
    recurrenceOnDay?: number;
    recurrenceOnMonth?: number;
    recurrenceType?: StandingInstructionData.RecurrenceTypeEnum;
    toAccount?: PortfolioAccountData;
    toAccountType?: StandingInstructionData.ToAccountTypeEnum;
    toClient?: ClientData;
    transferType?: StandingInstructionData.TransferTypeEnum;
    validFrom?: string;
}
export namespace StandingInstructionData {
    export const FromAccountTypeEnum = {
        Invalid: 'INVALID',
        Loan: 'LOAN',
        Savings: 'SAVINGS'
    } as const;
    export type FromAccountTypeEnum = typeof FromAccountTypeEnum[keyof typeof FromAccountTypeEnum];
    export const InstructionTypeEnum = {
        Invalid: 'INVALID',
        Fixed: 'FIXED',
        Dues: 'DUES'
    } as const;
    export type InstructionTypeEnum = typeof InstructionTypeEnum[keyof typeof InstructionTypeEnum];
    export const RecurrenceFrequencyEnum = {
        Days: 'DAYS',
        Weeks: 'WEEKS',
        Months: 'MONTHS',
        Years: 'YEARS',
        WholeTerm: 'WHOLE_TERM',
        Invalid: 'INVALID'
    } as const;
    export type RecurrenceFrequencyEnum = typeof RecurrenceFrequencyEnum[keyof typeof RecurrenceFrequencyEnum];
    export const RecurrenceTypeEnum = {
        Invalid: 'INVALID',
        Periodic: 'PERIODIC',
        AsPerDues: 'AS_PER_DUES'
    } as const;
    export type RecurrenceTypeEnum = typeof RecurrenceTypeEnum[keyof typeof RecurrenceTypeEnum];
    export const ToAccountTypeEnum = {
        Invalid: 'INVALID',
        Loan: 'LOAN',
        Savings: 'SAVINGS'
    } as const;
    export type ToAccountTypeEnum = typeof ToAccountTypeEnum[keyof typeof ToAccountTypeEnum];
    export const TransferTypeEnum = {
        Invalid: 'INVALID',
        AccountTransfer: 'ACCOUNT_TRANSFER',
        LoanRepayment: 'LOAN_REPAYMENT',
        ChargePayment: 'CHARGE_PAYMENT',
        InterestTransfer: 'INTEREST_TRANSFER',
        LoanDownPayment: 'LOAN_DOWN_PAYMENT'
    } as const;
    export type TransferTypeEnum = typeof TransferTypeEnum[keyof typeof TransferTypeEnum];
}


