/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StandingInstructionCreationRequest { 
    amount?: string;
    dateFormat?: string;
    fromAccountId?: string;
    fromAccountType?: string;
    fromClientId?: string;
    fromOfficeId?: string;
    instructionType?: string;
    locale?: string;
    monthDayFormat?: string;
    name?: string;
    priority?: string;
    recurrenceFrequency?: string;
    recurrenceInterval?: string;
    recurrenceOnMonthDay?: string;
    recurrenceType?: string;
    status?: string;
    toAccountId?: string;
    toAccountType?: string;
    toClientId?: string;
    toOfficeId?: string;
    transferType?: string;
    validFrom?: string;
    validTill?: string;
}

