/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionData } from './questionData';
import { ComponentData } from './componentData';


export interface SurveyData { 
    componentDatas?: Array<ComponentData>;
    countryCode?: string;
    description?: string;
    id?: number;
    key?: string;
    name?: string;
    questionDatas?: Array<QuestionData>;
    validFrom?: string;
    validTo?: string;
}

