/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Question } from './question';
import { Component } from './component';


export interface Survey { 
    components?: Array<Component>;
    countryCode?: string;
    description?: string;
    id?: number;
    key?: string;
    name?: string;
    'new'?: boolean;
    questions?: Array<Question>;
    validFrom?: string;
    validTo?: string;
}

