/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GLAccount } from './gLAccount';
import { TaxComponentHistory } from './taxComponentHistory';
import { TaxGroupMappings } from './taxGroupMappings';


export interface TaxComponent { 
    createdBy?: number;
    createdDate?: string;
    creditAccountType?: number;
    creditAcount?: GLAccount;
    debitAccountType?: number;
    debitAcount?: GLAccount;
    id?: number;
    lastModifiedBy?: number;
    lastModifiedDate?: string;
    'new'?: boolean;
    percentage?: number;
    taxComponentHistories?: Set<TaxComponentHistory>;
    taxGroupMappings?: Set<TaxGroupMappings>;
}

