/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxComponent } from './taxComponent';
import { TaxGroup } from './taxGroup';


export interface TaxGroupMappings { 
    createdBy?: number;
    createdDate?: string;
    endDate?: string;
    id?: number;
    lastModifiedBy?: number;
    lastModifiedDate?: string;
    'new'?: boolean;
    taxComponent?: TaxComponent;
    taxGroup?: TaxGroup;
}

