/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfficeData } from './officeData';
import { StaffData } from './staffData';


export interface TellerData { 
    creditAccountId?: number;
    debitAccountId?: number;
    description?: string;
    endDate?: string;
    hasMappedCashiers?: boolean;
    hasTransactions?: boolean;
    id?: number;
    name?: string;
    officeId?: number;
    officeName?: string;
    officeOptions?: Array<OfficeData>;
    staffOptions?: Array<StaffData>;
    startDate?: string;
    status?: TellerData.StatusEnum;
}
export namespace TellerData {
    export const StatusEnum = {
        Invalid: 'INVALID',
        Pending: 'PENDING',
        Active: 'ACTIVE',
        Inactive: 'INACTIVE',
        Closed: 'CLOSED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


