/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface TellerTransactionData { 
    amount?: number;
    cashierId?: number;
    clientId?: number;
    id?: number;
    officeId?: number;
    postingDate?: string;
    tellerId?: number;
    type?: EnumOptionData;
}

