/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionType } from './enumOptionType';
import { PaymentDetailData } from './paymentDetailData';
import { NoteData } from './noteData';


export interface TransactionDetails { 
    noteData?: NoteData;
    paymentDetails?: PaymentDetailData;
    transactionId?: number;
    transactionType?: EnumOptionType;
}

