/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * UpdatePostDatedCheckRequest
 */
export interface UpdatePostDatedCheckRequest { 
    accountNo?: number;
    amount?: number;
    date?: string;
    dateFormat?: string;
    locale?: string;
    name?: string;
    repaymentDate?: string;
}

