/**
 * Apache Fineract REST API
 *
 * Contact: dev@fineract.apache.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumOptionData } from './enumOptionData';


export interface WorkingDaysData { 
    extendTermForDailyRepayments?: boolean;
    extendTermForRepaymentsOnHolidays?: boolean;
    id?: number;
    recurrence?: string;
    repaymentRescheduleOptions?: Array<EnumOptionData>;
    repaymentRescheduleType?: EnumOptionData;
}

